init:
  parentPath: $parent.path
pipeline:

  test:
    action: http/runner:send
    requests:
      - Method: PUT
        URL: http://127.0.0.1:8080/v1/api/dev/basic/foos-updater
        JsonBody:
          - ID: 7
            Quantity: 123456
            Name: '035_ changed - foo 7'
          - ID: 8
            Name: '035_ changed - foo 8'
        Expect:
          Code: 200

  checkDB:
    action: 'dsunit:query'
    dataStore: dev
    SQL: |
      SELECT 
      (CASE  WHEN (SELECT COUNT(*) FROM FOOS WHERE ID = 7 AND QUANTITY = 123456 AND NAME ='035_ changed - foo 7' ) = 0 THEN FALSE ELSE TRUE END) AS UPDATED_ALL,
      (CASE WHEN (SELECT COUNT(*) FROM FOOS WHERE ID = 8 AND NAME = '035_ changed - foo 8' AND QUANTITY = 2500) THEN TRUE ELSE FALSE END) AS UPDATED_WITH_HAS;
    expect:
      - UPDATED_ALL: true
        UPDATED_WITH_HAS: true