init:
  AppVersion: $Cat(${appPath}/Version)

pipeline:

  deploy:
    set_sdk:
      action: sdk.set
      target: $target
      sdk: go:1.21

    package:
      action: exec:run
      comments: vendor build for deployment speedup
      target: $target
      checkError: true
      commands:
        - cd ${appPath}/cmd/datly
        - go mod vendor
        - go build
        - mv datly /tmp/datly
