init:
  parentPath: $parent.path
pipeline:

  test:
    action: http/runner:send
    requests:
      - Method: GET
        URL: http://127.0.0.1:8090/v1/api/dev/events/1
        Expect:
          Code: 200
          JSONBody: $LoadJSON('$parentPath/expect.json')

