package main

import (
	"bytes"
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/viant/datly/internal/testharness"
	"github.com/viant/datly/internal/testharness/manifestfree"
	"github.com/viant/datly/transcribe"
	xshape "github.com/viant/x/shape"
)

func TestLegacyReaderUpgradeWithoutManifest(t *testing.T) {
	type usecase struct {
		name string
		cli  bool
	}
	for _, tc := range []usecase{{"CLI", true}, {"API", false}} {
		t.Run(tc.name, func(t *testing.T) {
			ctx := context.Background()
			root := t.TempDir()
			const module = "github.com/viant/datly/testfixture/legacyreader"
			(testharness.GeneratedModule{Path: module}).Write(t, root)
			require.NoError(t, os.MkdirAll(filepath.Join(root, "source"), 0755))
			require.NoError(t, os.MkdirAll(filepath.Join(root, "contracts"), 0755))
			linked := "package contracts\ntype Key string\n"
			linkedPath := filepath.Join(root, "contracts", "key.go")
			require.NoError(t, os.WriteFile(linkedPath, []byte(linked), 0644))
			source := `#package('records')
#import('contracts','` + module + `/contracts')
#setting($_ = $route('/records','GET'))
#setting($_ = $case_format('lc'))
#setting($_ = $input_type('ApiKeyInput'))
#setting($_ = $output_type('ApiKeyOutput'))
#define($_ = $ID<int>(query/id).Optional())
#define($_ = $ApiKey<contracts.Key>(header/X-Api-Key).Optional())
#define($_ = $Data<[]*Record>(output/view))
SELECT r.id,r.name,type(r,'Record'),CAST(r.id AS int),CAST(r.name AS *string)
FROM records r`
			require.NoError(t, os.WriteFile(filepath.Join(root, "source", "api_key.dql"), []byte(source), 0644))
			request := func() transcribe.GenerationRequest {
				t.Helper()
				project, err := (&transcribe.Discovery{BaseDir: root, Include: []string{module + "/source"}}).Compile(ctx)
				require.NoError(t, err)
				require.Len(t, project.Components, 1)
				return transcribe.GenerationRequest{Compiled: project.Components[0], Destination: root}
			}
			seed, err := (transcribe.Generator{Operation: "get"}).Generate(ctx, request())
			require.NoError(t, err)
			dir := filepath.Join(root, "records")
			// Hydrate the old native output layout: scaffold comments and holder/embed
			// metadata survive, but none of the generated files has a standard header or
			// a package manifest. This includes methods-only input_setters.go.
			var generatedGo []string
			for _, file := range seed.Result.Files {
				if !strings.HasSuffix(file.Path, ".go") {
					continue
				}
				data, err := os.ReadFile(file.Path)
				require.NoError(t, err)
				parts := strings.SplitN(string(data), "\n\n", 2)
				require.Len(t, parts, 2)
				require.True(t, strings.HasPrefix(parts[0], "// Code generated by Datly for "))
				require.NoError(t, os.WriteFile(file.Path, []byte(parts[1]), 0644))
				generatedGo = append(generatedGo, file.Path)
			}
			setters := filepath.Join(dir, "input_setters.go")
			parsed, err := (xshape.SourceParser{}).ParseFile(setters)
			require.NoError(t, err)
			require.Empty(t, parsed.Declarations, "native declaration inventory deliberately excludes methods")
			data, err := os.ReadFile(setters)
			require.NoError(t, err)
			require.Contains(t, string(data), "SetID(")
			require.Contains(t, string(data), "SetApiKey(")
			require.NotContains(t, string(data), "Code generated")
			hooks := "package records\nimport \\\"context\\\"\nvar ApplicationInitCalls int\nfunc(*ApiKeyInput)Init(context.Context)error{ApplicationInitCalls++;return nil}\n"
			hooks = strings.ReplaceAll(hooks, `\"`, `"`)
			hookPath := filepath.Join(dir, "hooks.go")
			require.NoError(t, os.WriteFile(hookPath, []byte(hooks), 0644))
			runtime := strings.NewReplacer("HOLDER", seed.Result.Plan.HolderName(), "RecordsInput", "ApiKeyInput", "RecordsOutput", "ApiKeyOutput", "OPERATION", "get", "METHOD", "GET").Replace(manifestfree.RuntimeSource)
			runtime = strings.Replace(runtime, "import (", "import (\n \\\""+module+"/contracts\\\"", 1)
			runtime = strings.ReplaceAll(runtime, `\"`, `"`)
			runtime += `
func TestLegacySetters(t *testing.T){
 input:=&ApiKeyInput{}
 input.SetID(1);input.SetApiKey(contracts.Key("key"))
 if input.ID!=1||input.ApiKey!="key"||input.Has==nil||!input.Has.ID||!input.Has.ApiKey{t.Fatal("upgraded setter lost values or presence")}
}
`
			require.NoError(t, os.WriteFile(filepath.Join(dir, "runtime_test.go"), []byte(runtime), 0644))
			for attempt := 0; attempt < 2; attempt++ {
				if tc.cli {
					var out, diagnostic bytes.Buffer
					require.Equal(t, 0, generationCommand(ctx, []string{"transcribe", "get", "-dir", root, module + "/source"}, &out, &diagnostic), diagnostic.String())
				} else {
					_, err = (transcribe.Generator{Operation: "get"}).Generate(ctx, request())
					require.NoError(t, err)
				}
				for _, path := range generatedGo {
					data, err := os.ReadFile(path)
					require.NoError(t, err)
					require.True(t, strings.HasPrefix(string(data), "// Code generated by Datly for "), path)
				}
				for path, want := range map[string]string{hookPath: hooks, linkedPath: linked} {
					data, err := os.ReadFile(path)
					require.NoError(t, err)
					require.Equal(t, want, string(data))
				}
				require.NoError(t, filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
					if err != nil {
						return err
					}
					require.NotEqual(t, ".datly-gen.json", entry.Name())
					return nil
				}))
				command := exec.CommandContext(ctx, "go", "test", "-mod=mod", "-count=1", "./...")
				command.Dir = root
				out, err := command.CombinedOutput()
				require.NoError(t, err, "attempt %d: %s", attempt, out)
			}
		})
	}
}
