init:
  parentPath: $parent.path
  created: $FormatTime('nowInUTC', 'yyyy-MM-ddT00:00:00Z')
pipeline:

  test:
    action: http/runner:send
    requests:
      - Method: GET
        URL: http://127.0.0.1:8080/v1/api/shape/dev/vendors/
        Expect:
          Code: 200
          JSONBody: $LoadData('${parentPath}/expect.json')


      - Method: GET
        URL: http://127.0.0.1:8080/v1/api/meta/struct/dev/vendors/
        Expect:
          Code: 200
          Body: $Cat('${parentPath}/expect_2.txt')
#/v1/api/shape/dev/vendors?yy=id,vendorId&xx=id,name,products
