package diag

const (
	CodeParseEmpty          = "DQL-PARSE-EMPTY"
	CodeParseSyntax         = "DQL-PARSE-SYNTAX"
	CodeParseUnknownNonRead = "DQL-PARSE-UNKNOWN-NONREAD"

	CodeDirPackage     = "DQL-DIR-PACKAGE"
	CodeDirImport      = "DQL-DIR-IMPORT"
	CodeDirMeta        = "DQL-DIR-META"
	CodeDirCache       = "DQL-DIR-CACHE"
	CodeDirMCP         = "DQL-DIR-MCP"
	CodeDirConnector   = "DQL-DIR-CONNECTOR"
	CodeDirRoute       = "DQL-DIR-ROUTE"
	CodeDirMarshal     = "DQL-DIR-MARSHAL"
	CodeDirUnmarshal   = "DQL-DIR-UNMARSHAL"
	CodeDirFormat      = "DQL-DIR-FORMAT"
	CodeDirDateFormat  = "DQL-DIR-DATE-FORMAT"
	CodeDirCaseFormat  = "DQL-DIR-CASE-FORMAT"
	CodeDirUnsupported = "DQL-DIR-UNSUPPORTED"

	CodeOptParse          = "DQL-OPT-PARSE"
	CodeSQLIRawSelector   = "DQL-SQLI-RAW-SELECTOR"
	CodeViewMissingSQL    = "DQL-VIEW-MISSING-SQL"
	CodeViewCardinality   = "DQL-VIEW-CARDINALITY"
	CodeDeclOptionArgs    = "DQL-DECL-OPTION-ARGS"
	CodeDeclQuerySelector = "DQL-DECL-QUERY-SELECTOR"
	CodeRelMissingON      = "DQL-REL-MISSING-ON"
	CodeRelUnsupported    = "DQL-REL-UNSUPPORTED-PREDICATE"
	CodeRelAmbiguous      = "DQL-REL-AMBIGUOUS-LINK"
	CodeRelNoLinks        = "DQL-REL-NO-LINKS"
	CodeCompRefInvalid    = "DQL-COMP-REF-INVALID"
	CodeCompRouteMissing  = "DQL-COMP-ROUTE-MISSING"
	CodeCompRouteInvalid  = "DQL-COMP-ROUTE-INVALID"
	CodeCompCycle         = "DQL-COMP-CYCLE"
	CodeCompTypeCollision = "DQL-COMP-TYPE-COLLISION"
	CodeTypeCtxInvalid    = "DQL-TYPECTX-INVALID"
	CodeDMLMixed          = "DQL-DML-MIXED"
	CodeDMLServiceArg     = "DQL-DML-SERVICE-ARG"
	CodeDMLInsert         = "DQL-DML-INSERT"
	CodeDMLUpdate         = "DQL-DML-UPDATE"
	CodeDMLDelete         = "DQL-DML-DELETE"
	CodeColDiscoveryReq   = "DQL-COL-DISCOVERY-REQUIRED"

	PrefixRel  = "DQL-REL-"
	PrefixComp = "DQL-COMP-"
	PrefixSQLI = "DQL-SQLI-"
)
