pipeline:
  datly:
    stop:
      action: process:stop
      target: $target
      input: datly

    start:
      action: process:start
      sleepTimeMs: 6000
      target: $target
      directory: /tmp/
      checkError: true
      immuneToHangups: true
      env:
        TEST: 1
      command: pkill -f '${v1Path}/autogen/Datly/config.json -z=/tmp/jobs/datly_v1' >/dev/null 2>&1 || true; ulimit -Sn 10000 && ./datly -c=${v1Path}/autogen/Datly/config.json -z=/tmp/jobs/datly_v1 --mcpPort=8281 > /tmp/datly_v1.out 2>&1
