init:
  parentPath: $parent.path
pipeline:

  unauthorizedJWT:
    action: secret:signJWT
    privateKey:
      URL: ${appPath}/e2e/cloud/jwt/private.enc
      Key: blowfish://default
    claims:
      userID: 123
      firstName: Developer
      email: dev@viantint.com


  test:
    action: http/runner:send
    requests:
      - Method: POST
        URL: http://127.0.0.1:8080/v1/api/dev/comprehensive/parameters-order
        JSONBody:
            data: null

        Expect:
          Code: 401
          JSONBody: $LoadJSON('${parentPath}/expect_t0.json')

      - Method: POST
        URL: http://127.0.0.1:8080/v1/api/dev/comprehensive/parameters-order
        Header:
          Authorization: Bearer ${unauthorizedJWT.TokenString}
        JSONBody:
          data: null

        Expect:
          Code: 403
          JSONBody: $LoadJSON('${parentPath}/expect_t1.json')
