package patch_basic_one

import (
	"reflect"
	"github.com/viant/xdatly/types/core"
	"github.com/viant/xdatly/types/custom/dependency/checksum"
	"github.com/viant/xdatly/handler/response"
	"embed"
	"fmt"
	"context"
	"github.com/viant/datly/view"
	"github.com/viant/datly/repository"
	"github.com/viant/datly/repository/contract"
	"github.com/viant/datly"
	"github.com/viant/xdatly"
)

// Code generated by datly transcribe. DO NOT EDIT.

func init() {
	core.RegisterType("github.com/viant/datly/e2e/v1/shape/dev/events/patch_basic_one", "FoosInput", reflect.TypeOf(FoosInput{}), checksum.GeneratedTime)
	core.RegisterType("github.com/viant/datly/e2e/v1/shape/dev/events/patch_basic_one", "FoosOutput", reflect.TypeOf(FoosOutput{}), checksum.GeneratedTime)
	core.RegisterType("github.com/viant/datly/e2e/v1/shape/dev/events/patch_basic_one", "FoosView", reflect.TypeOf(FoosView{}), checksum.GeneratedTime)
	core.RegisterType("github.com/viant/datly/e2e/v1/shape/dev/events/patch_basic_one", "FoosInputHas", reflect.TypeOf(FoosInputHas{}), checksum.GeneratedTime)
}

//go:embed foos/*.sql
var FoosFS embed.FS

type FoosOutput struct {
	response.Status `parameter:",kind=output,in=status" json:",omitempty"`
	Foos FoosView `parameter:",kind=output,in="`
}

var FoosPathURI = "/v1/api/shape/dev/basic/foos"

func DefineFoosComponent(ctx context.Context, srv *datly.Service) error {
	aComponent, err := repository.NewComponent(
		contract.NewPath("PATCH", FoosPathURI),
		repository.WithResource(srv.Resource()),
		repository.WithContract(
			reflect.TypeOf(FoosInput{}),
			reflect.TypeOf(FoosOutput{}), &FoosFS, view.WithConnectorRef("dev")))

	if err != nil {
		return fmt.Errorf("failed to create Foos component: %w", err)
	}
	if err := srv.AddComponent(ctx, aComponent); err != nil {
		return fmt.Errorf("failed to add Foos component: %w", err)
	}
	return nil
}

type FoosRouter struct {
	Foos xdatly.Component[FoosInput, FoosOutput] `component:",path=/v1/api/shape/dev/basic/foos,method=PATCH,connector=dev,view=FoosView,source=foos/foos.sql"`
}

type FoosInput struct {
	Foos interface {} `parameter:",kind=body" typeName:"FoosView" anonymous:"true"`
	Has *FoosInputHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-"  typeName:"FoosInputHas"`
}

type FoosInputHas struct {
	Foos bool
}

func (i *FoosInput) EmbedFS() *embed.FS {
	return &FoosFS
}

type FoosView struct {
	Has *FoosViewHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"FoosViewHas"`
}

