init:
  mysqlSecrets:  ${secrets.$mysqlCredentials}
  arch: ''
  mysqlVer: 5.6
pipeline:
  checkArch:
    action: exec:run
    target: $target
    commands:
      - echo '${os.hardware}'

  adjustArch:
    action: nop
    when: $checkArch.Output:/arm/
    post:
      arch: arm64v8/
      mysqlVer: ''

  stop:
    services:
      action: docker:stop
      images:
        - mysql
        - aerospike
        - dynamodb-local

  start:
    services:
      mysql_dev:
        action: docker:run
        image: ${arch}mysql:${mysqlVer}
        name: mysql_dev
        ports:
          3306: 3306
        env:
          MYSQL_ROOT_PASSWORD: ${mysqlSecrets.Password}

      aerospike:
        action: docker:run
        image: '${arch}aerospike:ce-6.2.0.2'
        name: aero
        ports:
          3000: 3000
          3001: 3001
          3002: 3002

      dynamodb:
        action: docker:run
        image: 'amazon/dynamodb-local'
        name: dynamodb
        ports:
          8000: 8000
