package dml

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"testing"
	"time"

	"github.com/viant/sqlx/metadata/info/dialect"
	"github.com/viant/sqlx/testutil/reservationdb"
)

func TestSequenceLiveConcurrentWriters(t *testing.T) {
	for _, driver := range []string{"mysql", "postgres"} {
		for _, external := range []bool{false, true} {
			t.Run(fmt.Sprintf("%s/caller=%v", driver, external), func(t *testing.T) {
				h := reservationdb.Open(t, driver)
				h.CreateRecords(t)
				definition := "id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,parent_id BIGINT NOT NULL,FOREIGN KEY(parent_id) REFERENCES " + h.Table("records") + "(id)) ENGINE=InnoDB"
				if driver == "postgres" {
					definition = "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,parent_id BIGINT NOT NULL REFERENCES " + h.Table("records") + "(id))"
				}
				h.Exec(t, "CREATE TABLE "+h.Table("children")+" ("+definition)
				other := h.Other(t)
				h.DB.SetMaxOpenConns(1)
				other.SetMaxOpenConns(1)
				ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
				defer cancel()
				begun := make(chan struct{}, 2)
				start := make(chan struct{})
				allocated := make(chan int64, 2)
				release := make(chan struct{})
				done := make(chan error, 2)
				worker := func(db *sql.DB) {
					var tx *sql.Tx
					opts := []Option{WithSequenceStrategy(dialect.PresetIDWithReservation)}
					var err error
					if external {
						tx, err = db.BeginTx(ctx, nil)
						if err != nil {
							done <- err
							return
						}
						defer tx.Rollback()
						opts = append(opts, WithTx(tx))
					}
					data := NewData(db, opts...)
					err = data.BeginInvocation()
					if err == nil {
						err = data.Start(ctx)
					}
					begun <- struct{}{}
					select {
					case <-start:
					case <-ctx.Done():
						done <- ctx.Err()
						return
					}
					row := &concurrentSequenceRow{Name: "writer"}
					if err == nil {
						err = data.Allocate(ctx, h.Table("records"), row, "ID")
					}
					if err == nil {
						allocated <- row.ID
						select {
						case <-release:
						case <-ctx.Done():
							err = ctx.Err()
						}
					}
					if err == nil {
						err = data.Insert(h.Table("records"), row)
					}
					type child struct {
						ID       int64 `sqlx:"id,primaryKey,autoincrement"`
						ParentID int64 `sqlx:"parent_id"`
					}
					c := &child{ParentID: row.ID}
					if err == nil {
						err = data.Allocate(ctx, h.Table("children"), c, "ID")
					}
					if err == nil {
						err = data.Insert(h.Table("children"), c)
					}
					err = data.Complete(ctx, err)
					if err == nil && external {
						err = tx.Commit()
					}
					done <- err
				}
				go worker(h.DB)
				go worker(other)
				for i := 0; i < 2; i++ {
					select {
					case <-begun:
					case err := <-done:
						t.Fatal(err)
					case <-ctx.Done():
						t.Fatal(ctx.Err())
					}
				}
				close(start)
				var first, second int64
				select {
				case first = <-allocated:
				case err := <-done:
					t.Fatal(err)
				case <-ctx.Done():
					t.Fatal(ctx.Err())
				}
				if driver == "postgres" {
					select {
					case second = <-allocated:
					case err := <-done:
						t.Fatal(err)
					case <-ctx.Done():
						t.Fatal("nextval blocked another caller:", ctx.Err())
					}
				} else {
					select {
					case id := <-allocated:
						t.Fatalf("MySQL second writer escaped pending reservation: %d", id)
					case err := <-done:
						t.Fatal(err)
					case <-time.After(100 * time.Millisecond):
					}
				}
				close(release)
				completed := 0
				if driver == "mysql" {
					for second == 0 {
						select {
						case second = <-allocated:
						case err := <-done:
							if err != nil {
								t.Fatal(err)
							}
							completed++
						case <-ctx.Done():
							t.Fatal(ctx.Err())
						}
					}
				}

				if first == 0 || second == 0 || first == second {
					t.Fatalf("duplicate IDs %d/%d", first, second)
				}
				for i := completed; i < 2; i++ {
					select {
					case err := <-done:
						if err != nil {
							t.Fatal(err)
						}
					case <-ctx.Done():
						t.Fatal(ctx.Err())
					}
				}
				var count int
				if err := h.DB.QueryRowContext(ctx, "SELECT count(*) FROM "+h.Table("children")+" c JOIN "+h.Table("records")+" r ON c.parent_id=r.id").Scan(&count); err != nil || count != 2 {
					t.Fatalf("queued stable FK identity: %d %v", count, err)
				}
			})
		}
	}
}

func TestSequenceLiveCallerFinalizationFailure(t *testing.T) {
	for _, driver := range []string{"mysql", "postgres"} {
		t.Run(driver, func(t *testing.T) {
			h := reservationdb.Open(t, driver)
			h.CreateRecords(t)
			h.DB.SetMaxOpenConns(1)
			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
			defer cancel()
			tx, err := h.DB.BeginTx(ctx, nil)
			if err != nil {
				t.Fatal(err)
			}
			defer tx.Rollback()
			if _, err = tx.ExecContext(ctx, "INSERT INTO "+h.Table("records")+"(name) VALUES('caller')"); err != nil {
				t.Fatal(err)
			}
			data := NewData(h.DB, WithTx(tx), WithSequenceStrategy(dialect.PresetIDWithReservation))
			if err = data.BeginInvocation(); err != nil {
				t.Fatal(err)
			}
			row := &concurrentSequenceRow{Name: "queued"}
			if err = data.Allocate(ctx, h.Table("records"), row, "ID"); err != nil {
				t.Fatal(err)
			}
			if err = data.Insert(h.Table("records"), row); err != nil {
				t.Fatal(err)
			}
			cause := errors.New("finalizer failure")
			if err = data.Complete(ctx, cause); !errors.Is(err, cause) {
				t.Fatal(err)
			}
			var n int
			if err = tx.QueryRowContext(ctx, "SELECT count(*) FROM "+h.Table("records")).Scan(&n); err != nil || n != 1 {
				t.Fatalf("caller work/ownership changed: %d %v", n, err)
			}
			if err = tx.Rollback(); err != nil {
				t.Fatal(err)
			}
			if h.Count(t, "records") != 0 {
				t.Fatal("caller work committed")
			}
		})
	}
}
