package transcribe

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/viant/datly/internal/testharness"
	gen "github.com/viant/datly/transcribe/generate"
	"github.com/viant/datly/transcribe/testdata/outputrows"
	"github.com/viant/datly/typecatalog"
	"github.com/viant/x"
)

const declaredOutputRowDQL = `#package('generated')
#import('rows','github.com/viant/datly/transcribe/testdata/outputrows')
#setting($_ = $route('/records', 'GET'))
#set($_ = $Scope<string>(query/scope))
#set($_ = $Data<[]*rows.Row>(output/view))
SELECT record.*, metrics.*, use_connector(metrics, 'offline')
FROM (SELECT id FROM records WHERE owner=$Scope) record
JOIN (SELECT id, stamp, spend FROM metrics) metrics ON record.id=metrics.id
`

func TestTranscribeGetLinksDeclaredOutputRowWithoutDatabase(t *testing.T) {
	root := t.TempDir()
	testharness.WriteGeneratedGoMod(t, root)
	catalog := typecatalog.NewCatalog()
	require.NoError(t, catalog.Register(typecatalog.TypeOriginPackage, x.NewType(reflect.TypeFor[outputrows.Row]())))
	generated, err := NewCompiler().Transcribe(context.Background(), Request{
		Destination: root,
		Source:      &Source{Scope: "example.com/generated/dql/records", Name: "Records", Types: catalog, Text: declaredOutputRowDQL},
		Generation:  GenerationOptions{Operation: "get"},
	})
	require.NoError(t, err)
	plan := generated.Result.Plan
	require.Len(t, plan.Views, 1)
	require.Equal(t, gen.ViewLinked, plan.Views[0].Ownership)
	require.Equal(t, "github.com/viant/datly/transcribe/testdata/outputrows", plan.Views[0].Package)
	require.Equal(t, "rows.Row", plan.RootViewType)
	for _, file := range generated.Result.Files {
		require.NotContains(t, file.Content, "type Row struct")
		require.NotContains(t, file.Content, "type MetricsView struct")
		if strings.HasSuffix(file.Path, "output.go") {
			require.Contains(t, file.Content, "[]*rows.Row")
		}
	}
}

func TestDeclaredOutputRowRequiresAuthority(t *testing.T) {
	_, err := NewCompiler().Compile(context.Background(), &Source{Scope: "example.com/generated/dql/records", Name: "Records", Types: typecatalog.NewCatalog(), Text: declaredOutputRowDQL})
	require.ErrorContains(t, err, "requires existing named Go type authority")
}

func TestTranscribeGetPreservesLocalLinkedRowsAndSQLResources(t *testing.T) {
	root := t.TempDir()
	testharness.WriteGeneratedGoMod(t, root)
	packagePath := "example.com/generated/records"
	dir := filepath.Join(root, "records")
	fixtureSource, err := os.ReadFile("testdata/outputrows/rows.go")
	require.NoError(t, err)
	rowSource := "// Code generated by Datly for Records; DO NOT EDIT.\n" + strings.Replace(string(fixtureSource), "package outputrows", "package records", 1)
	initial := &gen.Plan{
		Package: packagePath, GoPackage: "records", ComponentName: "Records", RouterDest: "router.go",
		Input:     gen.ContractPlan{Type: "RecordsInput", Destination: "input.go", Ownership: gen.ContractGenerated},
		Output:    gen.ContractPlan{Type: "RecordsOutput", Destination: "output.go", Ownership: gen.ContractGenerated},
		Resources: &gen.ResourcePlan{Namespace: "original_records", Destination: "resources.go", Symbol: "Records", Files: []gen.EmittedFile{{Path: "sql/metrics.sql", Content: "SELECT id, stamp, spend FROM metrics"}}},
	}
	_, err = gen.EmitScaffold(dir, initial)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(filepath.Join(dir, "views.go"), []byte(rowSource), 0600))
	catalog := typecatalog.NewCatalog()
	require.NoError(t, catalog.Register(typecatalog.TypeOriginPackage, x.NewType(reflect.TypeFor[outputrows.Row](), x.WithPkgPath(packagePath))))
	require.NoError(t, catalog.Register(typecatalog.TypeOriginPackage, x.NewType(reflect.TypeFor[outputrows.Total](), x.WithPkgPath(packagePath))))
	source := strings.ReplaceAll(declaredOutputRowDQL, "#package('generated')", "#package('records')")
	source = strings.ReplaceAll(source, "github.com/viant/datly/transcribe/testdata/outputrows", packagePath)
	source = strings.Replace(source, "SELECT record.*", "#set($_ = $Meta<*rows.Total>(output/summary) /* SELECT COUNT(1) AS count FROM records */)\nSELECT record.*", 1)
	for i := 0; i < 2; i++ {
		generated, err := NewCompiler().Transcribe(context.Background(), Request{Destination: root,
			Source:     &Source{Scope: "example.com/generated/dql/records", Name: "Records", Types: catalog, Text: source},
			Generation: GenerationOptions{Operation: "get"},
		})
		require.NoError(t, err)
		require.Equal(t, "original_records", generated.Result.Plan.Resources.Namespace)
		require.Len(t, generated.Result.Plan.Views, 2)
		for _, view := range generated.Result.Plan.Views {
			require.Equal(t, gen.ViewLinked, view.Ownership)
		}
		actual, err := os.ReadFile(filepath.Join(dir, "views.go"))
		require.NoError(t, err)
		require.Equal(t, rowSource, string(actual))
		actual, err = os.ReadFile(filepath.Join(dir, "sql/metrics.sql"))
		require.NoError(t, err)
		require.Equal(t, "SELECT id, stamp, spend FROM metrics", string(actual))
		actual, err = os.ReadFile(filepath.Join(dir, "output.go"))
		require.NoError(t, err)
		require.Contains(t, string(actual), "[]*Row")
		require.NotContains(t, string(actual), "dataType=[]*rows.Row")
		require.Contains(t, string(actual), "dataType=[]*example.com/generated/records.Row")
		require.Contains(t, string(actual), "dataType=*example.com/generated/records.Total")
		require.Contains(t, string(actual), "original_records:sql/records.sql")
	}
	// A generated derived row cannot replace a file owning a linked root.
	_, err = NewCompiler().Transcribe(context.Background(), Request{Destination: root,
		Source:     &Source{Scope: "example.com/generated/dql/records", Name: "Records", Types: catalog, Text: strings.Replace(source, "Meta<*rows.Total>", "Meta<?>", 1)},
		Generation: GenerationOptions{Operation: "get"},
	})
	require.ErrorContains(t, err, "contains a linked Go type")
	actual, err := os.ReadFile(filepath.Join(dir, "views.go"))
	require.NoError(t, err)
	require.Equal(t, rowSource, string(actual))
}
