package transcribe

import (
	"context"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/viant/datly/internal/testharness"
	"github.com/viant/datly/transcribe/column"
	"github.com/viant/datly/transcribe/generate"
	"github.com/viant/datly/typecatalog"
)

const primaryPackageModule = "github.com/viant/datly/primarypackagefixture"
const primaryPackageDirectory = "api/lightbyadvertiser"

func primaryPackageFixture(t *testing.T) (string, *Source) {
	t.Helper()
	root := t.TempDir()
	(testharness.GeneratedModule{Path: primaryPackageModule}).Write(t, root)
	db := testharness.NewSQLiteHarness(t)
	require.NoError(t, db.ExecStatements(context.Background(), "CREATE TABLE RECORDS(ID INTEGER PRIMARY KEY,NAME TEXT)"))
	return root, &Source{Name: "Lightbyadvertiser", Scope: "example.com/source", Types: typecatalog.NewCatalog(), Connector: "main", ColumnRefiner: column.New(column.Connections{"main": db.DB}), Text: `#package('` + primaryPackageModule + `/` + primaryPackageDirectory + `')
#setting($_ = $route('/records','GET'))
#set($_ = $Id<int>(query/id).Optional())
SELECT ID, NAME FROM RECORDS`}
}

func writePrimaryPackageFile(t *testing.T, root, name, content string) {
	t.Helper()
	path := filepath.Join(root, primaryPackageDirectory, name)
	require.NoError(t, os.MkdirAll(filepath.Dir(path), 0700))
	require.NoError(t, os.WriteFile(path, []byte(content), 0600))
}

// Snapshots include names, modes, bytes and symlink targets without reading
// nonregular files or following a link outside the disposable fixture.
func primaryPackageSnapshot(t *testing.T, root string) map[string]string {
	t.Helper()
	result := map[string]string{}
	require.NoError(t, filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		value := info.Mode().String()
		if info.Mode().IsRegular() {
			data, e := os.ReadFile(path)
			if e != nil {
				return e
			}
			value += string(data)
		}
		if info.Mode()&os.ModeSymlink != 0 {
			link, e := os.Readlink(path)
			if e != nil {
				return e
			}
			value += link
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		result[relative] = value
		return nil
	}))
	return result
}

func TestGeneratorPreservesExistingPrimaryPackage(t *testing.T) {
	for _, kind := range []string{"authored hook", "coherent generated", "stale generated body", "generated only"} {
		t.Run(kind, func(t *testing.T) {
			root, source := primaryPackageFixture(t)
			hook := `package campaign
import "context"
var currentInput *LightbyadvertiserInput
func (o *LightbyadvertiserOutput) Finalize(context.Context) error {
 currentInput = &LightbyadvertiserInput{Id: 7}
 return nil
}
`
			if kind != "generated only" {
				writePrimaryPackageFile(t, root, "lightbyadvertiser_hook.go", hook)
			}
			if kind != "authored hook" {
				body := "type Obsolete struct{}\n"
				if kind == "stale generated body" {
					body = "this is invalid stale generated syntax {\n"
				}
				writePrimaryPackageFile(t, root, "input.go", "// Code generated by Datly for Lightbyadvertiser; DO NOT EDIT.\n\npackage campaign\n"+body)
			}
			// Neither same-package nor external tests may supply package identity.
			writePrimaryPackageFile(t, root, "unrelated_test.go", "package campaign_test\n")
			writePrimaryPackageFile(t, root, "another_test.go", "package campaign\n")
			g := Generator{Operation: "get"}
			got, err := g.Generate(context.Background(), GenerationRequest{Source: source, Destination: root})
			require.NoError(t, err)
			require.Equal(t, "campaign", got.Result.Plan.GoPackage)
			require.Equal(t, primaryPackageModule+"/"+primaryPackageDirectory, got.Package.PkgPath)
			require.Equal(t, "LightbyadvertiserComponent", got.Result.Plan.HolderName())
			entries, err := os.ReadDir(filepath.Join(root, primaryPackageDirectory))
			require.NoError(t, err)
			for _, entry := range entries {
				if !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
					continue
				}
				file, err := parser.ParseFile(token.NewFileSet(), filepath.Join(root, primaryPackageDirectory, entry.Name()), nil, parser.PackageClauseOnly)
				require.NoError(t, err)
				require.Equal(t, "campaign", file.Name.Name, entry.Name())
			}
			before := primaryPackageSnapshot(t, root)
			_, err = g.Generate(context.Background(), GenerationRequest{Source: source, Destination: root})
			require.NoError(t, err)
			require.Equal(t, before, primaryPackageSnapshot(t, root), "complete regeneration bytes and filenames")
			if kind != "generated only" {
				data, err := os.ReadFile(filepath.Join(root, primaryPackageDirectory, "lightbyadvertiser_hook.go"))
				require.NoError(t, err)
				require.Equal(t, hook, string(data))
			}
			// Compile every production artifact together with the authored hook.
			cmd := exec.Command("go", "build", "-mod=readonly", "./"+primaryPackageDirectory)
			cmd.Dir = root
			out, err := cmd.CombinedOutput()
			require.NoError(t, err, "%s", out)
		})
	}
}

func TestGeneratorExistingPrimaryPackageDefaults(t *testing.T) {
	for _, kind := range []string{"missing", "empty", "tests only"} {
		t.Run(kind, func(t *testing.T) {
			root, source := primaryPackageFixture(t)
			if kind != "missing" {
				require.NoError(t, os.MkdirAll(filepath.Join(root, primaryPackageDirectory), 0700))
			}
			if kind == "tests only" {
				writePrimaryPackageFile(t, root, "external_test.go", "package other_test\n")
				writePrimaryPackageFile(t, root, "invalid_test.go", "not even a package clause\n")
			}
			got, err := (Generator{Operation: "get"}).Generate(context.Background(), GenerationRequest{Source: source, Destination: root})
			require.NoError(t, err)
			require.Equal(t, "lightbyadvertiser", got.Result.Plan.GoPackage)
			require.Equal(t, "LightbyadvertiserComponent", got.Result.Plan.HolderName())
		})
	}
	t.Run("low level no package", func(t *testing.T) {
		root, source := primaryPackageFixture(t)
		source.Text = strings.Replace(source.Text, "#package('"+primaryPackageModule+"/"+primaryPackageDirectory+"')\n", "", 1)
		compiled, err := NewCompiler().Compile(context.Background(), source)
		require.NoError(t, err)
		require.NoError(t, os.MkdirAll(filepath.Join(root, "generated"), 0700))
		require.NoError(t, os.WriteFile(filepath.Join(root, "generated", "existing.go"), []byte("package lightbyadvertiser\n"), 0600))
		input, dir, err := generationInput(root, "generated", compiled)
		require.NoError(t, err)
		require.Empty(t, input.PackageName)
		require.Equal(t, "generated", dir)
		plan, err := generate.New(input).Plan()
		require.NoError(t, err)
		require.Empty(t, plan.GoPackage)
		require.Equal(t, "Component", plan.HolderName())
		got, err := NewCompiler().generateCompiled(context.Background(), root, compiled)
		require.NoError(t, err)
		require.Equal(t, "lightbyadvertiser", got.Result.Plan.PackageName())
		require.Equal(t, "Component", got.Result.Plan.HolderName())
	})
}

func TestGeneratorExistingPrimaryPackageRejectsBeforeWriting(t *testing.T) {
	for _, tc := range []struct{ name, first, second, diagnostic string }{
		{"missing clause", "func Missing() {}\n", "", "a.go"},
		{"invalid clause", "package 123\n", "", "a.go"},
		{"keyword", "package func\n", "", "a.go"},
		{"underscore", "package _\n", "", "invalid Go package name"},
		{"mixed production", "package campaign\n", "package other\n", "b.go"},
		{"authored generated conflict", "package campaign\n", "// Code generated by Datly for Lightbyadvertiser; DO NOT EDIT.\npackage lightbyadvertiser\n", "b.go"},
		{"tagged mixed production", "package campaign\n", "//go:build excluded\n\npackage other\n", "b.go"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			root, source := primaryPackageFixture(t)
			writePrimaryPackageFile(t, root, "a.go", tc.first)
			if tc.second != "" {
				writePrimaryPackageFile(t, root, "b.go", tc.second)
			}
			before := primaryPackageSnapshot(t, root)
			for attempt := 0; attempt < 2; attempt++ {
				_, err := (Generator{Operation: "get"}).Generate(context.Background(), GenerationRequest{Source: source, Destination: root})
				require.ErrorContains(t, err, tc.diagnostic)
				if tc.second != "" {
					require.ErrorContains(t, err, "conflicting with \"campaign\" in")
					require.ErrorContains(t, err, "a.go")
				}
				require.Equal(t, before, primaryPackageSnapshot(t, root))
			}
		})
	}
	t.Run("invalid destination basename", func(t *testing.T) {
		root, source := primaryPackageFixture(t)
		source.Text = strings.Replace(source.Text, primaryPackageDirectory, "api/not-a-package", 1)
		dir := filepath.Join(root, "api/not-a-package")
		require.NoError(t, os.MkdirAll(dir, 0700))
		require.NoError(t, os.WriteFile(filepath.Join(dir, "existing.go"), []byte("package campaign\n"), 0600))
		before := primaryPackageSnapshot(t, root)
		_, err := (Generator{Operation: "get"}).Generate(context.Background(), GenerationRequest{Source: source, Destination: root})
		require.ErrorContains(t, err, "invalid Go package name")
		require.Equal(t, before, primaryPackageSnapshot(t, root))
	})
	for _, kind := range []string{"file symlink", "destination symlink", "nested module"} {
		t.Run(kind, func(t *testing.T) {
			root, source := primaryPackageFixture(t)
			outside := t.TempDir()
			require.NoError(t, os.WriteFile(filepath.Join(outside, "external.go"), []byte("package campaign\n"), 0600))
			require.NoError(t, os.MkdirAll(filepath.Join(root, "api"), 0700))
			destination := filepath.Join(root, primaryPackageDirectory)
			if kind == "destination symlink" {
				require.NoError(t, os.Symlink(outside, destination))
			} else {
				require.NoError(t, os.MkdirAll(destination, 0700))
				if kind == "file symlink" {
					require.NoError(t, os.Symlink(filepath.Join(outside, "external.go"), filepath.Join(destination, "a.go")))
				} else {
					require.NoError(t, os.WriteFile(filepath.Join(destination, "go.mod"), []byte("module nested\n"), 0600))
				}
			}
			before, externalBefore := primaryPackageSnapshot(t, root), primaryPackageSnapshot(t, outside)
			_, err := (Generator{Operation: "get"}).Generate(context.Background(), GenerationRequest{Source: source, Destination: root})
			require.Error(t, err)
			require.Equal(t, before, primaryPackageSnapshot(t, root))
			require.Equal(t, externalBefore, primaryPackageSnapshot(t, outside))
		})
	}
}

func TestExistingPrimaryPackageClauseOnly(t *testing.T) {
	root := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(root, "authored.go"), []byte("package campaign\ninvalid stale body {\n"), 0600))
	require.NoError(t, os.MkdirAll(filepath.Join(root, "ignored.go"), 0700))
	name, err := existingPrimaryPackageName(root)
	require.NoError(t, err)
	require.Equal(t, "campaign", name)
	_, err = existingPrimaryPackageName(filepath.Join(root, "authored.go"))
	require.Error(t, err)
}
