pipeline:
  datly:
    stop:
      action: process:stop
      target: $target
      input: datly

    copyAssets:
      action: exec:run
      comments: copy assets
      target: $target
      checkError: true
      commands:
        - cp -r ${appPath}/e2e/local/assets/. ${appPath}/e2e/local/autogen/Datly/assets/



    start:
      action: process:start
      sleepTimeMs: 6000
      target: $target
      directory: /tmp/
      checkError: true
      immuneToHangups: true
      env:
        TEST: 1
        DATLY_NOPANIC: 1
      command: ulimit -Sn 10000 && ./datly -c=$appPath/e2e/local/autogen/Datly/config.json > /tmp/datly.out

  validator:
    stop:
      action: process:stop
      target: $target
      input: validator_24

    start:
      action: process:start
      sleepTimeMs: 3000
      target: $target
      directory: /tmp/
      checkError: true
      immuneToHangups: true
      env:
        TEST: 1
        VALIDATOR_PORT: 8871

      command: ./validator_24