pipeline:
  datly:
    stop:
      action: process:stop
      target: $target
      input: datly

    start:
      action: process:start
      sleepTimeMs: 3000
      target: $target
      directory: /tmp/
      checkError: true
      immuneToHangups: true
      env:
        TEST: 1
      command: ./datly -c=$appPath/e2e/local/autogen/Datly/config.json > /tmp/datly.out

  validator:
    stop:
      action: process:stop
      target: $target
      input: validator_24

    start:
      action: process:start
      sleepTimeMs: 3000
      target: $target
      directory: /tmp/
      checkError: true
      immuneToHangups: true
      env:
        TEST: 1
        VALIDATOR_PORT: 8871
      command: ./validator_24