init:
pipeline:
  set_sdk:
    action: sdk.set
    target: $target
    sdk: go:1.17

  database:
    action: run
    request: '@db'

  rule:
    description: generate datly rule with SQLx (SQL extension)
    action: run
    request: '@rule'

  app:
    when: $debugger!=on
    description: start datly app with rule generted from SQLs
    action: run
    request: '@app'

  test:
    run_tests:
      tag: $pathMatch
      description: '@info'
      data:
        '[]gen': '@gen'

      subPath: 'cases/${index}_*'
      range: 1..050
      template:
        checkSkip:
          action: nop
          comments: use case init
          skip: $HasResource(${path}/skip.txt)
        test:
          action: run
          request: '@test'


