init:

pipeline:

#  rule:
#    description: generate datly rule with SQLx (SQL extension)
#    action: run
#    request: '@rule'

  app:
    description: start datly app with rule generted from SQLs
    action: run
    request: '@app'

  test:
    tag: $pathMatch
    description: '@info'

    subPath: 'cases/${index}_*'
    data:
      '[]gen': '@gen'

    range: 1..001
    template:
      checkSkip:
        action: nop
        comments: use case init
        skip: $HasResource(${path}/skip.txt)
      test:
        action: run
        request: '@test'

