init:
  AppVersion: $Cat(${appPath}/Version)
  appPath: $WorkingDirectory(./../..)
pipeline:
  deploy:
    set_sdk:
      action: sdk.set
      target: $target
      sdk: go:1.21

    cleanupXDatly:
      action: exec:run
      description: clean previous tests
      target: '$target'
      checkError: true
      commands:
        - mkdir -p ${appPath}/e2e/custom_datly/.extension
        - rm -rf ${appPath}/e2e/custom_datly/.extension

    initExtensionModule:
      action: exec:run
      comments: init xdatly extension module
      target: $target
      checkError: true
      commands:
        - cd ${appPath}/e2e/custom_datly
        - rm -f -rf .extension
        - cd $appPath/cmd/datly
        - go build -tags debug
        - cp datly /tmp/datly
        - /tmp/datly initExt -p='${appPath}/e2e/custom_datly/.extension' -n=datly_ext -g=github.com/viant

    copyDatly:
      action: exec:run
      comments: copy datly project
      target: $target
      checkError: true
      commands:
        - export GLOBIGNORE='e2e*'
        - echo 'THE APP PATH IS -> $appPath'
        - cd ${appPath}/e2e/custom_datly
        - rm -rf ${appPath}/e2e/custom_datly/.extension/.build/datly
        - rsync -av --progress ../../ .extension/.build/datly --exclude e2e

    package:
      action: exec:run
      comments: vendor build for deployment speedup
      target: $target
      checkError: true
      commands:
        - export GO111MODULE=on
        - cd ${appPath}/cmd/datly
        - go mod download
        - go build -ldflags "-X main.BuildTimeInS=`date +%s`" -trimpath
        - mv datly /tmp/datly
