init:
  AppVersion: $Cat(${appPath}/Version)
  appPath: $WorkingDirectory(./../..)
pipeline:
  deploy:
    set_sdk:
      action: sdk.set
      target: $target
      sdk: go:1.17


    pullXDatly:
      action: exec:run
      skip: $HasResource(${appPath}/e2e/custom_datly/.xdatly/.gitignore)
      comments: copy datly project
      target: $target
      checkError: true
      commands:
        - cd ${appPath}/e2e/custom_datly
        - git clone https://github.com/viant/xdatly.git .xdatly

    updateXDatly:
      action: exec:run
      comments: copy datly project
      target: $target
      checkError: true
      commands:
        - cd ${appPath}/e2e/custom_datly/.xdatly/
        - echo 'Current directory \/'
        - pwd
        - git stash
        - git pull --rebase
        - cd ${appPath}/e2e/custom_datly/.xdatly/types/custom
        - go get github.com/francoispqt/gojay@1398296
        - cp ${appPath}/e2e/custom_datly/imports.go ${appPath}/e2e/custom_datly/.xdatly/types/custom/dependency
        - go mod tidy -compat=1.17

    copyDatly:
      action: exec:run
      comments: copy datly project
      target: $target
      checkError: true
      commands:
        - export GLOBIGNORE='e2e*'
        - echo 'THE APP PATH IS -> $appPath'
        - cd ${appPath}/e2e/custom_datly
        - rm -rf .datly
        - rsync -av --progress ../../ .datly/ --exclude e2e

    package:
      action: exec:run
      comments: vendor build for deployment speedup
      target: $target
      checkError: true
      commands:
        - export GO111MODULE=on
        - cd ${appPath}/cmd/datly
        - go mod download
        - go build -ldflags "-X main.BuildTimeInS=`date +%s`" -trimpath
        - mv datly /tmp/datly
