init:
  parentPath: $parent.path
pipeline:

  test:
    action: http/runner:send
    requests:
      - Method: POST
        URL: http://127.0.0.1:8080/v1/api/dev/basic/events-one-one
        JsonBody:
          Quantity: -5678
          EventsPerformance:
            Price: -6789
        Expect:
          Code: 200
          JSONBody: $LoadJSON('${parentPath}/expect_t0.json')

  checkDB:
    action: 'dsunit:query'
    dataStore: dev
    SQL: |
      SELECT 
      (CASE  WHEN (SELECT COUNT(*) FROM EVENTS WHERE QUANTITY = -5678) = 0 THEN FALSE ELSE TRUE END) AS EVENTS_ADDED,
      (CASE  WHEN (SELECT COUNT(*) FROM EVENTS_PERFORMANCE WHERE PRICE = -6789) = 0 THEN FALSE ELSE TRUE END) AS EVENTS_PERFORMANCE_ADDED ;
    expect:
      - EVENTS_ADDED: true
        EVENTS_PERFORMANCE_ADDED: true