package golang

import (
	"bytes"
	"fmt"
	"github.com/viant/datly/internal/testharness"
	"github.com/viant/datly/spec"
	plan "github.com/viant/datly/transcribe/handler/ast"
	"go/ast"
	"go/format"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func runEntitySyncFixture(t *testing.T, semantic *plan.Plan, types []RecordType, source string, products ...*ast.File) {
	t.Helper()
	asset, err := EntitySupport(semantic, Config{Package: "events", Factory: "NewEventsHandler", InputType: "Input", OutputType: "Output", Records: types})
	if err != nil {
		t.Fatal(err)
	}
	(entitySyncFixture{entity: asset, products: products, source: source}).run(t)
}

type entitySyncFixture struct {
	entity      *EntityAsset
	products    []*ast.File
	source      string
	withoutRace bool
}

func (f entitySyncFixture) run(t *testing.T) {
	t.Helper()
	var generated bytes.Buffer
	if err := format.Node(&generated, token.NewFileSet(), f.entity.File); err != nil {
		t.Fatal(err)
	}
	directory := t.TempDir()
	(testharness.GeneratedModule{Path: "github.com/viant/datly/syncfixture"}).Write(t, directory)
	for name, content := range map[string][]byte{"entities.go": generated.Bytes(), "entities_test.go": []byte(f.source)} {
		if err := os.WriteFile(filepath.Join(directory, name), content, 0644); err != nil {
			t.Fatal(err)
		}
	}
	for index, product := range f.products {
		if product == f.entity.File {
			continue
		}
		var content bytes.Buffer
		if err := format.Node(&content, token.NewFileSet(), product); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(directory, fmt.Sprintf("product%d.go", index)), content.Bytes(), 0644); err != nil {
			t.Fatal(err)
		}
	}
	arguments := []string{"test"}
	if !f.withoutRace {
		arguments = append(arguments, "-race")
	}
	arguments = append(arguments, "-mod=mod", "-timeout=60s", "./...")
	command := exec.Command("go", arguments...)
	command.Dir = directory
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("generated recursive sync: %v\n%s\n%s", err, output, generated.Bytes())
	}
}

func TestRecursivePresenceSelfGraphs(t *testing.T) {
	for _, pointer := range []bool{true, false} {
		t.Run(map[bool]string{true: "pointer", false: "value"}[pointer], func(t *testing.T) {
			semantic := rootSemanticPlan(plan.OperationPost, true)
			prefix := ""
			if pointer {
				prefix = "*"
			}
			semantic.Root.Entity = &plan.EntityPlan{Type: spec.TypeRef{Name: "Node", Package: "events"}, MarkerField: "Has", MarkerPointer: true, Keys: semantic.Root.Keys, Fields: []plan.EntityField{{Name: "Id", Type: spec.TypeRef{Name: "*int64"}, Identity: true, Writable: true}, {Name: "TenantId", Type: spec.TypeRef{Name: "int64"}, Identity: true, Writable: true}, {Name: "Name", Type: spec.TypeRef{Name: "string"}, Writable: true}, {Name: "Children", Type: spec.TypeRef{Name: "[]" + prefix + "Node"}, Relation: true, Self: true, Writable: true}, {Name: "Next", Type: spec.TypeRef{Name: "*Node"}, Relation: true, Self: true, Writable: true}}}
			source := strings.ReplaceAll(selfSyncFixture, "{{P}}", prefix)
			scenario := pointerSelfScenario
			if !pointer {
				scenario = valueSelfScenario
			}
			source = strings.ReplaceAll(source, "{{SCENARIO}}", scenario)
			runEntitySyncFixture(t, semantic, rootRecordTypes(semantic, "[]"+prefix+"Node", ""), source)
		})
	}
}

const selfSyncFixture = `package events
import("context";"testing")
type Flag bool
type Flags struct{Id,TenantId,Name,Children,Next Flag}
type NodeHas struct{*Flags;Version int;service func()}
type MarkerPointer *NodeHas
type Node struct{Id *int64;TenantId int64;Name string;Children []{{P}}Node;Next *Node;Has MarkerPointer;service func()}
type Input struct{Events []{{P}}Node}
type Output struct{Data []{{P}}Node}
func capture(t *testing.T,input *Input)*_newEventsHandlerOriginalInput{t.Helper();value,err:=_newEventsHandlerCaptureInput(context.Background(),input);if err!=nil{t.Fatal(err)};return value.(*_newEventsHandlerOriginalInput)}
{{SCENARIO}}
`

const pointerSelfScenario = `func TestSelfGraph(t *testing.T){
 zero:=int64(0);root:=&Node{Id:&zero,TenantId:1,Name:"supplied",Has:&NodeHas{Flags:&Flags{Id:true,TenantId:true,Name:true},Version:9,service:func(){}},service:func(){}}
 tail:=root
 for i:=int64(1);i<=512;i++{id:=i;next:=&Node{Id:&id,TenantId:1,Has:&NodeHas{Flags:&Flags{Id:true,TenantId:true}}};tail.Next=next;tail=next}
 root.Children=[]*Node{tail};tail.Next=root
 input:=&Input{Events:[]*Node{root}};snapshot:=capture(t,input)
 root.Has.Name=false;tail.Name="changed"
 if err:=snapshot.SyncPresence(input);err!=nil{t.Fatal(err)}
 if !bool(root.Has.Name)||!bool(tail.Has.Name)||root.Has.Version!=9||root.Has.service==nil{t.Fatal("deep/self flags or untouched marker state lost")}
 if snapshot.Roots[0].original==root||snapshot.Roots[0].original.Children[0].Next!=snapshot.Roots[0].original{t.Fatal("self baseline cycle not detached intact")}
 if !snapshot.Roots[0].Has("Name")||snapshot.records0[tail].Has("Name"){t.Fatal("original markers changed")}
}
func TestNilNestedNamedMarkersAndOriginalIdentity(t *testing.T){
 id:=int64(7);node:=&Node{Id:&id,TenantId:4,Has:&NodeHas{Version:3}};input:=&Input{Events:[]*Node{node}};snapshot:=capture(t,input)
 node.Name="new";id=91
 if err:=snapshot.SyncPresence(input);err!=nil{t.Fatal(err)}
 if node.Has.Flags==nil||!bool(node.Has.Name)||bool(node.Has.Id)||node.Has.Version!=3{t.Fatal("named/nil nested marker patch is wrong")}
 if snapshot.Roots[0].Has("Id")||snapshot.Roots[0].original.Has.Flags!=nil{t.Fatal("identity inferred from later values or original marker mutated")}
}
func TestCompositeDuplicateAtomicity(t *testing.T){
 one,two:=int64(0),int64(0);a:=&Node{Id:&one,TenantId:4,Has:&NodeHas{Flags:&Flags{Id:true,TenantId:true}}};b:=&Node{Id:&two,TenantId:4,Has:&NodeHas{Flags:&Flags{Id:true,TenantId:true}}};input:=&Input{Events:[]*Node{a,b}};snapshot:=capture(t,input);a.Name="changed"
 if err:=snapshot.SyncPresence(input);err==nil{t.Fatal("duplicate explicit zero tuple accepted")};if bool(a.Has.Name)||bool(b.Has.Name){t.Fatal("error changed markers")}
}
func TestPartialOriginalIdentity(t *testing.T){
 id:=int64(2);node:=&Node{Id:&id,TenantId:4,Has:&NodeHas{Flags:&Flags{Id:true}}};input:=&Input{Events:[]*Node{node}};snapshot:=capture(t,input);node.Name="changed"
 if err:=snapshot.SyncPresence(input);err==nil{t.Fatal("partial original identity accepted")};if bool(node.Has.Name){t.Fatal("partial identity failure changed markers")}
}
`

const valueSelfScenario = `func TestValueSelfCycle(t *testing.T){
 id:=int64(0);rows:=[]Node{{Id:&id,TenantId:1,Name:"before",Has:&NodeHas{Flags:&Flags{Id:true,TenantId:true}}}};rows[0].Children=rows
 input:=&Input{Events:rows};snapshot:=capture(t,input);input.Events[0].Name="changed"
 if err:=snapshot.SyncPresence(input);err!=nil{t.Fatal(err)};if !bool(input.Events[0].Has.Name){t.Fatal("value cycle did not sync")}
 original:=snapshot.Roots[0].original;if original.Name!="before"||&original.Children[0]!=original{t.Fatal("value slice baseline cycle lost")}
}
func TestValueAssociation(t *testing.T){
 for _,mode:=range []string{"reorder","reorder and mutate","unassigned mutate","unassigned unchanged","unassigned entity entry"}{t.Run(mode,func(t *testing.T){
  first,second:=int64(1),int64(2);rows:=[]Node{{Id:&first,TenantId:1,Name:"first",Has:&NodeHas{Flags:&Flags{Id:true,TenantId:true}}},{Id:&second,TenantId:1,Name:"second",Has:&NodeHas{Flags:&Flags{Id:true,TenantId:true}}}}
  if mode=="unassigned mutate"||mode=="unassigned unchanged"||mode=="unassigned entity entry"{rows[0].Has.Flags=&Flags{};rows[1].Has.Flags=&Flags{}}
  input:=&Input{Events:rows};snapshot:=capture(t,input)
  if mode=="reorder"||mode=="reorder and mutate"{input.Events=[]Node{rows[1],rows[0]}}
  invalid:=mode=="reorder and mutate"||mode=="unassigned mutate"||mode=="unassigned entity entry";if invalid{input.Events[0].Name="changed"}
  var err error;if mode=="unassigned entity entry"{err=snapshot.Roots[0].SyncPresence(&input.Events[0])}else{err=snapshot.SyncPresence(input)};if (err!=nil)!=invalid{t.Fatalf("sync error = %v",err)}
  if invalid&&(bool(input.Events[0].Has.Name)||bool(input.Events[1].Has.Name)){t.Fatal("ambiguous value error changed markers")}
 })}
}
`

func TestRecursivePresenceEmbeddedBusiness(t *testing.T) {
	semantic := rootSemanticPlan(plan.OperationPost, false)
	semantic.Root.Entity = &plan.EntityPlan{Type: spec.TypeRef{Name: "Record", Package: "events"}, MarkerField: "Has", MarkerPointer: true, Keys: semantic.Root.Keys, Fields: []plan.EntityField{{Name: "Id", Path: plan.FieldPath{"Base", "Id"}, Type: spec.TypeRef{Name: "*int64"}, Identity: true, Writable: true}, {Name: "Name", Path: plan.FieldPath{"Base", "Name"}, Type: spec.TypeRef{Name: "string"}, Writable: true}, {Name: "Value", Path: plan.FieldPath{"Base", "Value"}, Type: spec.TypeRef{Name: "int"}, Writable: true}, {Name: "Children", Path: plan.FieldPath{"Base", "Children"}, Type: spec.TypeRef{Name: "[]*Record"}, Relation: true, Self: true, Writable: true}}}
	runEntitySyncFixture(t, semantic, rootRecordTypes(semantic, "[]*Record", ""), embeddedSyncFixture)
}

const embeddedSyncFixture = `package events
import("context";"testing")
type Marker struct{Id,Name,Value,Children bool}
type Base struct{Id *int64;Name string;Value int;Children []*Record;service func()}
type Record struct{*Base;Has *Marker}
type Input struct{Events []*Record}
type Output struct{Data []*Record}
func TestEmbeddedBusiness(t *testing.T){
 for _,mode:=range []string{"nil to value","empty holder","nil holder"}{t.Run(mode,func(t *testing.T){
  record:=&Record{Has:&Marker{}}
  if mode!="nil to value"{record.Base=&Base{service:func(){}}}
  if mode=="nil holder"{id:=int64(1);child:=&Record{Base:&Base{Id:&id},Has:&Marker{Id:true}};record.Children=[]*Record{child}}
  input:=&Input{Events:[]*Record{record}};captured,err:=_newEventsHandlerCaptureInput(context.Background(),input);if err!=nil{t.Fatal(err)};snapshot:=captured.(*_newEventsHandlerOriginalInput)
  switch mode{case "nil to value":record.Base=&Base{Value:7,service:func(){}};case "empty holder":record.Children=[]*Record{};case "nil holder":record.Base=nil}
  if err:=snapshot.SyncPresence(input);err!=nil{t.Fatal(err)}
  if mode=="nil to value"{if !record.Has.Value||record.Has.Name||record.Has.Children||record.Base.service==nil{t.Fatal("allocating one business field marked sibling or copied services")};if snapshot.Roots[0].original.Base!=nil{t.Fatal("nil baseline embedding fabricated")}}
  if mode=="empty holder"&&!record.Has.Children{t.Fatal("empty/nil nested relation membership not marked")}
  if mode=="nil holder"&&(!record.Has.Children||record.Base!=nil){t.Fatal("nil relation holder not handled without business allocation")}
 })}
}
`

func TestRecursivePresenceMultipleProjections(t *testing.T) {
	semantic := recursiveSemanticPlan(plan.OperationPost)
	root := semantic.Root
	child := root.Relations[0].Child
	leaf := child.Relations[0].Child
	root.Entity = &plan.EntityPlan{Owned: true, Type: spec.TypeRef{Name: "Order"}, MarkerField: "Has", MarkerPointer: true, MarkerType: spec.TypeRef{Name: "OrderHas"}, Fields: []plan.EntityField{{Name: "Id", Type: spec.TypeRef{Name: "*int64"}, Identity: true, Writable: true}, {Name: "Items", Type: spec.TypeRef{Name: "[]*Node"}, Relation: true, Writable: true}}}
	child.Entity = &plan.EntityPlan{Owned: true, Type: spec.TypeRef{Name: "Node"}, MarkerField: "Has", MarkerPointer: true, MarkerType: spec.TypeRef{Name: "NodeHas"}, Fields: []plan.EntityField{{Name: "Id", Type: spec.TypeRef{Name: "*int64"}, Identity: true, Writable: true}, {Name: "Name", Type: spec.TypeRef{Name: "string"}, Writable: true}, {Name: "Details", Type: spec.TypeRef{Name: "[]*Node"}, Relation: true, Writable: true}}}
	leaf.Entity = &plan.EntityPlan{Owned: true, Type: spec.TypeRef{Name: "Node"}, MarkerField: "Has", MarkerPointer: true, MarkerType: spec.TypeRef{Name: "NodeHas"}, Fields: []plan.EntityField{{Name: "Id", Type: spec.TypeRef{Name: "*int64"}, Identity: true, Writable: true}, {Name: "Enabled", Type: spec.TypeRef{Name: "bool"}, Writable: true}}}
	types := []RecordType{{Identity: root.Identity, Path: root.InputPath, Value: "[]*Order"}, {Identity: child.Identity, Path: child.InputPath, Value: "[]*Node"}, {Identity: leaf.Identity, Path: leaf.InputPath, Value: "[]*Node"}}
	runEntitySyncFixture(t, semantic, types, projectionSyncFixture)
}

const projectionSyncFixture = `package events
import("context";"testing")
type OrderHas struct{Id,Items bool}
type NodeHas struct{Id,Name,Enabled,Details bool;Version int}
type Order struct{Id *int64;Items []*Node;Has *OrderHas}
type Node struct{Id *int64;Name string;Enabled bool;Details []*Node;Has *NodeHas}
type Input struct{Orders []*Order}
type Output struct{Data []*Order}
func TestProjectionSync(t *testing.T){
 id:=int64(1);node:=&Node{Id:&id,Name:"before",Has:&NodeHas{Id:true,Version:4}};node.Details=[]*Node{node};input:=&Input{Orders:[]*Order{{Id:&id,Items:[]*Node{node},Has:&OrderHas{Id:true}}}}
 captured,err:=_newEventsHandlerCaptureInput(context.Background(),input);if err!=nil{t.Fatal(err)};snapshot:=captured.(*_newEventsHandlerOriginalInput)
 before:=node.Has;node.Name="after";node.Enabled=true
 associations,err:=snapshot.synchronize(input);if err!=nil{t.Fatal(err)}
 if !node.Has.Name||!node.Has.Enabled||node.Has.Version!=4{t.Fatal("one projection overwrote another marker patch")}
 if before.Name||before.Enabled{t.Fatal("working marker preparation modified shared prior marker")}
 if associations.matched1[node]==nil||associations.matched2[node]==nil{t.Fatal("path-specific association missing")}
 if associations.matched1[node].Has("Name")||associations.matched2[node].Has("Enabled"){t.Fatal("original presence mutated")}
}
`

func TestRecursivePresenceMissingMarkerAncestorIsAtomic(t *testing.T) {
	semantic := rootSemanticPlan(plan.OperationPost, false)
	semantic.Root.Entity = &plan.EntityPlan{Type: spec.TypeRef{Name: "Record", Package: "events"}, MarkerField: "Has", MarkerPointer: true, Keys: semantic.Root.Keys, Fields: []plan.EntityField{{Name: "Id", Path: plan.FieldPath{"Base", "Id"}, Type: spec.TypeRef{Name: "*int64"}, Identity: true, Writable: true}, {Name: "Name", Path: plan.FieldPath{"Base", "Name"}, Type: spec.TypeRef{Name: "string"}, Writable: true}}}
	runEntitySyncFixture(t, semantic, rootRecordTypes(semantic, "[]*Record", ""), missingMarkerAncestorFixture)
}

const missingMarkerAncestorFixture = `package events
import("context";"testing")
type Marker struct{Id,Name bool}
type Base struct{Id *int64;Name string;Has *Marker;service func()}
type Record struct{*Base}
type Input struct{Events []*Record}
type Output struct{Data []*Record}
func TestMissingMarkerAncestor(t *testing.T){
 one,two:=int64(1),int64(2);first:=&Record{Base:&Base{Id:&one,Name:"first",Has:&Marker{Id:true}}};second:=&Record{Base:&Base{Id:&two,Name:"second",Has:&Marker{Id:true,Name:true}}};input:=&Input{Events:[]*Record{first,second}}
 captured,err:=_newEventsHandlerCaptureInput(context.Background(),input);if err!=nil{t.Fatal(err)};snapshot:=captured.(*_newEventsHandlerOriginalInput);before:=first.Has
 first.Name="changed";second.Base=nil
 if err:=snapshot.SyncPresence(input);err==nil{t.Fatal("missing business ancestor for marker was silently allocated")}
 if first.Has!=before||first.Has.Name||second.Base!=nil{t.Fatal("error partially changed markers or business state")}
}
`

func TestRecursivePresenceGenericSingletonSelfAndValueMarker(t *testing.T) {
	semantic := rootSemanticPlan(plan.OperationPost, false)
	semantic.Root.Entity = &plan.EntityPlan{Type: spec.TypeRef{Name: "Node[int]", Package: "events"}, MarkerField: "Has", Keys: semantic.Root.Keys, Fields: []plan.EntityField{{Name: "Id", Type: spec.TypeRef{Name: "*int64"}, Identity: true, Writable: true}, {Name: "Name", Type: spec.TypeRef{Name: "int"}, Writable: true}, {Name: "Next", Type: spec.TypeRef{Name: "Node[int]", Package: "events", Pointer: true}, Relation: true, Self: true, Writable: true}}}
	runEntitySyncFixture(t, semantic, rootRecordTypes(semantic, "[]*Node[int]", ""), genericSelfFixture)
}

const genericSelfFixture = `package events
import("context";"testing")
type Flag bool
type Marker struct{Id,Name,Next Flag;Version int}
type Node[T any]struct{Id *int64;Name T;Next *Node[T];Has Marker}
type Input struct{Events []*Node[int]}
type Output struct{Data []*Node[int]}
func TestGenericSelf(t *testing.T){
 id:=int64(1);node:=&Node[int]{Id:&id,Name:1,Has:Marker{Id:true,Version:8}};node.Next=node;input:=&Input{Events:[]*Node[int]{node}}
 captured,err:=_newEventsHandlerCaptureInput(context.Background(),input);if err!=nil{t.Fatal(err)};snapshot:=captured.(*_newEventsHandlerOriginalInput)
 node.Name=2;if err:=snapshot.SyncPresence(input);err!=nil{t.Fatal(err)}
 if !bool(node.Has.Name)||!bool(node.Has.Id)||node.Has.Version!=8{t.Fatal("value/named marker patch failed")}
 if snapshot.Roots[0].Has("Name")||snapshot.Roots[0].original.Name!=1||snapshot.Roots[0].original.Next!=snapshot.Roots[0].original{t.Fatal("generic singleton self baseline changed")}
}
`
