package column

import (
	"context"
	"database/sql"
	"errors"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"github.com/viant/datly/internal/testharness/sqlite"
	"github.com/viant/datly/spec"
	"github.com/viant/datly/transcribe/generate"
	"github.com/viant/sqlx/testutil/sqlfault"
)

type metadataCalls struct {
	mu       sync.Mutex
	counts   map[string]int
	failKind string
	failErr  error
}

func metadataQueryKind(query string) string {
	query = strings.ToLower(query)
	switch {
	case strings.Contains(query, "sqlite_version()"):
		return "product"
	case strings.Contains(query, "pragma_database_list"):
		return "session"
	case strings.Contains(query, "pragma_table_info"):
		return "columns"
	case strings.Contains(query, "pragma_foreign_key_list"):
		return "foreign_keys"
	default:
		return "output"
	}
}

func (c *metadataCalls) before(_ context.Context, call sqlfault.Call) error {
	if call.Phase != "query" {
		return nil
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	kind := metadataQueryKind(call.SQL)
	if c.counts == nil {
		c.counts = make(map[string]int)
	}
	c.counts[kind]++
	if kind == c.failKind {
		return c.failErr
	}
	return nil
}

func (c *metadataCalls) snapshot() map[string]int {
	c.mu.Lock()
	defer c.mu.Unlock()
	result := make(map[string]int)
	for key, count := range c.counts {
		result[key] = count
	}
	return result
}

func metadataDB(t *testing.T, calls *metadataCalls) *sql.DB {
	t.Helper()
	h := sqlite.New(t)
	require.NoError(t, h.ExecStatements(context.Background(),
		"CREATE TABLE owners(id INTEGER PRIMARY KEY)",
		"CREATE TABLE records(id INTEGER PRIMARY KEY, owner_id INTEGER NOT NULL REFERENCES owners(id), name TEXT DEFAULT 'new')"))
	return h.FaultDB(t, calls.before)
}

func metadataComponent() *spec.Component {
	view := func(name string) *spec.View {
		return &spec.View{Name: name, Source: &spec.ViewSource{SQL: "SELECT id, owner_id, name FROM records"}}
	}
	return &spec.Component{
		Name: "Records", Key: spec.Key{Kind: spec.KindComponent, Name: "Records"},
		Routes:   []*spec.Route{{Method: "GET", Path: "/records"}},
		Settings: &spec.Settings{DefaultConnector: "main"},
		RootView: view("Records"), Views: []*spec.View{view("OtherRecords")},
	}
}

func TestCompilationMetadataReuseAndArtifactParity(t *testing.T) {
	ctx := context.Background()
	calls := &metadataCalls{}
	db := metadataDB(t, calls)
	r := New(Connections{"main": db})
	component := metadataComponent()
	compilation := r.BeginCompilation()
	require.NoError(t, compilation.RefineRoot(ctx, component, nil, nil))
	require.NoError(t, compilation.RefineViews(ctx, component, nil, nil))
	require.Equal(t, map[string]int{"product": 1, "session": 1, "columns": 2, "foreign_keys": 2, "output": 2}, calls.snapshot())
	require.True(t, component.RootView.Columns[0].PrimaryKey)
	require.True(t, component.RootView.Columns[1].NotNull)
	require.Contains(t, component.RootView.Columns[1].Tag, "refTable=owners")
	require.NotNil(t, component.RootView.Columns[2].Default)

	// One-shot phase calls intentionally do not share metadata. Their complete
	// discovered contracts and generated bytes must match the shared-state path.
	baseline := metadataComponent()
	require.NoError(t, r.RefineRoot(ctx, baseline, nil, nil))
	require.NoError(t, r.RefineViews(ctx, baseline, nil, nil))
	require.Equal(t, baseline, component)
	var files [][]generate.EmittedFile
	for _, item := range []*spec.Component{baseline, component} {
		dir := t.TempDir()
		result, err := generate.New(generate.Input{Component: item, PackageName: "records", TargetPackage: "example.com/records", SQLResources: true, EphemeralOwnership: true}).Generate(dir)
		require.NoError(t, err)
		for i := range result.Files {
			result.Files[i].Path, err = filepath.Rel(dir, result.Files[i].Path)
			require.NoError(t, err)
		}
		files = append(files, result.Files)
	}
	require.NotEmpty(t, files[0])
	require.Equal(t, files[0], files[1])
	require.Equal(t, map[string]int{"product": 3, "session": 3, "columns": 4, "foreign_keys": 4, "output": 4}, calls.snapshot())

	// A reusable Refiner must never retain the preceding compilation's cache.
	require.NoError(t, r.Refine(ctx, metadataComponent(), nil, nil))
	require.Equal(t, map[string]int{"product": 4, "session": 4, "columns": 6, "foreign_keys": 6, "output": 6}, calls.snapshot())
}

func TestCompilationMetadataConcurrentRefinerReuse(t *testing.T) {
	calls := &metadataCalls{}
	db := metadataDB(t, calls)
	r := New(Connections{"main": db})
	const workers = 8
	errs := make(chan error, workers)
	for i := 0; i < workers; i++ {
		go func() { errs <- r.Refine(context.Background(), metadataComponent(), nil, nil) }()
	}
	for i := 0; i < workers; i++ {
		require.NoError(t, <-errs)
	}
	require.Equal(t, map[string]int{"product": workers, "session": workers, "columns": 2 * workers, "foreign_keys": 2 * workers, "output": 2 * workers}, calls.snapshot())
}

func TestCompilationMetadataPoolIsolation(t *testing.T) {
	first, second := &metadataCalls{}, &metadataCalls{}
	db1, db2 := metadataDB(t, first), metadataDB(t, second)
	r := New(Connections{"main": db1, "alias": db1, "other": db2})
	component := metadataComponent()
	component.Views[0].Source.Bindings = &spec.ViewBindings{Connector: "alias"}
	other := component.Views[0].Clone()
	other.Name = "OtherDatabase"
	other.Source.Bindings.Connector = "other"
	component.Views = append(component.Views, other)
	require.NoError(t, r.Refine(context.Background(), component, nil, nil))
	require.Equal(t, map[string]int{"product": 1, "session": 1, "columns": 2, "foreign_keys": 2, "output": 2}, first.snapshot())
	require.Equal(t, map[string]int{"product": 1, "session": 1, "columns": 1, "foreign_keys": 1, "output": 1}, second.snapshot())
}

func TestCompilationMetadataFailureRetry(t *testing.T) {
	for _, kind := range []string{"product", "session", "columns", "foreign_keys", "output"} {
		for _, failure := range []error{errors.New("discovery unavailable"), context.Canceled} {
			t.Run(kind+"/"+failure.Error(), func(t *testing.T) {
				calls := &metadataCalls{failKind: kind, failErr: failure}
				db := metadataDB(t, calls)
				compilation := New(Connections{"main": db}).BeginCompilation()
				err := compilation.RefineRoot(context.Background(), metadataComponent(), nil, nil)
				require.ErrorIs(t, err, failure)
				failedCalls := calls.snapshot()[kind]
				calls.mu.Lock()
				calls.failKind = ""
				calls.mu.Unlock()
				require.NoError(t, compilation.RefineRoot(context.Background(), metadataComponent(), nil, nil))
				counts := calls.snapshot()
				require.Equal(t, failedCalls+1, counts[kind], "failed discovery must execute on retry")
				if kind != "product" {
					require.Equal(t, 1, counts["product"])
				}
				if kind != "product" && kind != "session" {
					require.Equal(t, 1, counts["session"])
				}
			})
		}
	}
}

func TestCompilationMetadataCopiesAndCancellation(t *testing.T) {
	calls := &metadataCalls{}
	db := metadataDB(t, calls)
	m := &discoveryMetadata{}
	ctx := context.Background()
	product, err := m.product(ctx, db)
	require.NoError(t, err)
	wantProduct := *product
	session, err := m.session(ctx, db, product)
	require.NoError(t, err)
	wantSession := *session
	product.Name = "changed"
	session.Schema = "changed"
	product, err = m.product(ctx, db)
	require.NoError(t, err)
	require.Equal(t, wantProduct, *product)
	session, err = m.session(ctx, db, product)
	require.NoError(t, err)
	require.Equal(t, wantSession, *session)
	for _, state := range []*discoveryMetadata{m, {}} {
		canceled, cancel := context.WithCancel(ctx)
		cancel()
		_, err = state.product(canceled, db)
		require.ErrorIs(t, err, context.Canceled)
		_, err = state.session(canceled, db, product)
		require.ErrorIs(t, err, context.Canceled)
	}
	require.Equal(t, map[string]int{"product": 1, "session": 1}, calls.snapshot())
}

func TestCompilationMetadataInFlightCancellation(t *testing.T) {
	h := sqlite.New(t)
	started := make(chan struct{})
	var attempts atomic.Int32
	db := h.FaultDB(t, func(ctx context.Context, call sqlfault.Call) error {
		if call.Phase == "query" && metadataQueryKind(call.SQL) == "session" && attempts.Add(1) == 1 {
			close(started)
			<-ctx.Done()
			return ctx.Err()
		}
		return nil
	})
	m := &discoveryMetadata{}
	product, err := m.product(context.Background(), db)
	require.NoError(t, err)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	done := make(chan error, 1)
	go func() { _, err := m.session(ctx, db, product); done <- err }()
	select {
	case <-started:
		cancel()
	case <-ctx.Done():
		t.Fatal("session discovery did not start")
	}
	require.ErrorIs(t, <-done, context.Canceled)
	_, err = m.session(context.Background(), db, product)
	require.NoError(t, err)
	require.EqualValues(t, 2, attempts.Load(), "canceled session must not be cached")
}
