init:
  parentPath: $parent.path
  expect: $LoadJSON('${parentPath}/expect.json')
pipeline:
  signJWT:
    action: secret:signJWT
    privateKey:
      URL: ${appPath}/e2e/cloud/jwt/private.enc
      Key: blowfish://default
    claims:
      userID: 2
      firstName: Developer
      email: dev@viantint.com

  printToken:
    action: print
    message: Bearer ${signJWT.TokenString}


  test:
    testAuthenticatedAndAuthorized:
      action: http/runner:send
      requests:
      - Method: GET
        description: user is authenticated and authorized for vendor 2
        URL: http://127.0.0.1:8080/v1/api/dev/vendors-async/2
        Header:
          Authorization: Bearer ${signJWT.TokenString}
        Expect:
          Code: 200
          JSONBody: $expect
