init:
  parentPath: $parent.path
pipeline:

  test:
    action: http/runner:send
    requests:
      - Method: POST
        URL: http://127.0.0.1:8080/v1/api/dev/basic/events
        JsonBody:
          Name: '017_'
        Expect:
          Code: 200
          JSONBody: $LoadJSON('${parentPath}/expect_t0.json')

      - Method: POST
        URL: http://127.0.0.1:8080/v1/api/dev/basic/events
        JSONBody:
          Name: "017_ Custom name"
          Quantity: 25
        Expect:
          Code: 200
          JSONBody: $LoadJSON('${parentPath}/expect_t1.json')

  checkDB:
    action: 'dsunit:query'
    dataStore: dev
    SQL: |
      SELECT (CASE  WHEN COUNT(*) = 0 THEN FALSE ELSE TRUE END) AS ADDED_NEW_ROWS FROM ( SELECT * FROM EVENTS WHERE NAME LIKE '017_%') T;
    expect:
      - ADDED_NEW_ROWS: true