package xgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/viant/datly/repository/shape/dql/shape"
	shapeload "github.com/viant/datly/repository/shape/load"
	"github.com/viant/datly/repository/shape/typectx"
	"github.com/viant/datly/view"
	"github.com/viant/datly/view/state"
	"github.com/viant/tagly/format/text"
	"github.com/viant/xreflect"
	"reflect"
)

// ComponentCodegen generates Go source code for a complete component package:
// Input struct, Output struct, entity view structs, init() registration,
// //go:embed directive, and DefineComponent function.
//
// This is the shape pipeline equivalent of repository.Component.GenerateOutputCode.
type ComponentCodegen struct {
	Component    *shapeload.Component
	Resource     *view.Resource
	TypeContext  *typectx.Context
	ProjectDir   string
	PackageDir   string
	PackageName  string
	PackagePath  string
	FileName     string // defaults to <component_name>.go
	WithEmbed    bool   // generate //go:embed and EmbedFS method
	WithContract bool   // generate DefineComponent function
	WithRegister *bool  // generate init() with core.RegisterType (default: true)
}

// ComponentCodegenResult captures generation outputs.
type ComponentCodegenResult struct {
	FilePath    string
	PackagePath string
	PackageName string
	Types       []string
	Embeds      map[string]string // SQL file name → SQL content
}

// Generate produces the component Go source file.
func (g *ComponentCodegen) Generate() (*ComponentCodegenResult, error) {
	if g.Component == nil {
		return nil, fmt.Errorf("shape codegen: nil component")
	}
	if g.Resource == nil {
		return nil, fmt.Errorf("shape codegen: nil resource")
	}

	projectDir := g.ProjectDir
	if projectDir == "" {
		return nil, fmt.Errorf("shape codegen: project dir required")
	}

	packageDir := g.PackageDir
	if packageDir == "" && g.TypeContext != nil {
		packageDir = g.TypeContext.PackageDir
	}
	if packageDir == "" {
		return nil, fmt.Errorf("shape codegen: package dir required")
	}
	if !filepath.IsAbs(packageDir) {
		packageDir = filepath.Join(projectDir, packageDir)
	}

	packageName := g.PackageName
	if packageName == "" && g.TypeContext != nil {
		packageName = g.TypeContext.PackageName
	}
	if packageName == "" {
		packageName = filepath.Base(packageDir)
	}

	packagePath := g.PackagePath
	if packagePath == "" && g.TypeContext != nil {
		packagePath = g.TypeContext.PackagePath
	}

	componentName := g.componentName()
	embedURI := text.CaseFormatUpperCamel.Format(componentName, text.CaseFormatLowerUnderscore)

	fileName := g.FileName
	if fileName == "" {
		fileName = embedURI + ".go"
	}

	// First generate view shapes via xgen (for entity structs like VendorView, ProductsView)
	shapeDoc := resourceToCodegenDoc(g.Resource, g.TypeContext)
	shapeCfg := &Config{
		ProjectDir:  projectDir,
		PackageDir:  packageDir,
		PackageName: packageName,
		PackagePath: packagePath,
		FileName:    "shapes_gen.go",
	}
	shapeResult, _ := GenerateFromDQLShape(shapeDoc, shapeCfg)

	// Build Input/Output types using state.Parameters.ReflectType
	lookupType := func(name string, opts ...xreflect.Option) (reflect.Type, error) {
		return nil, fmt.Errorf("type %s not found", name)
	}

	var inputType, outputType reflect.Type
	if params := g.Component.InputParameters(); len(params) > 0 {
		rt, err := params.ReflectType(packagePath, lookupType, state.WithSetMarker(), state.WithTypeName(componentName+"Input"))
		if err == nil && rt != nil {
			inputType = rt
		}
	}

	// Build output parameters — use explicit ones or synthesize defaults for readers
	outputParams := g.Component.OutputParameters()
	hasExplicitOutput := len(outputParams) > 0
	if !hasExplicitOutput {
		outputParams = g.defaultOutputParameters(componentName)
	}
	// Resolve wildcard output types to the view entity type
	g.resolveOutputWildcardTypes(outputParams, componentName)
	if len(outputParams) > 0 {
		rt, err := outputParams.ReflectType(packagePath, lookupType)
		if err == nil && rt != nil {
			outputType = rt
		}
	}

	// Build the Go source
	var builder strings.Builder
	builder.WriteString("package " + packageName + "\n\n")

	// Imports
	imports := g.buildImports()
	if len(imports) > 0 {
		builder.WriteString("import (\n")
		for _, imp := range imports {
			if strings.Contains(imp, " ") {
				// aliased import
				builder.WriteString("\t" + imp + "\n")
			} else {
				builder.WriteString("\t\"" + imp + "\"\n")
			}
		}
		builder.WriteString(")\n\n")
	}

	// Code generated header
	builder.WriteString("// Code generated by datly transcribe. DO NOT EDIT.\n\n")

	// init() registration
	builder.WriteString("func init() {\n")
	if g.withRegister() {
		if inputType != nil {
			builder.WriteString(fmt.Sprintf("\tcore.RegisterType(%q, %q, reflect.TypeOf(%sInput{}), checksum.GeneratedTime)\n",
				packageName, componentName+"Input", componentName))
		}
		builder.WriteString(fmt.Sprintf("\tcore.RegisterType(%q, %q, reflect.TypeOf(%sOutput{}), checksum.GeneratedTime)\n",
			packageName, componentName+"Output", componentName))
	}
	builder.WriteString("}\n\n")

	// //go:embed
	if g.WithEmbed {
		builder.WriteString(fmt.Sprintf("//go:embed %s/*.sql\n", embedURI))
		builder.WriteString(fmt.Sprintf("var %sFS embed.FS\n\n", componentName))
	}

	// Input struct
	if inputType != nil {
		builder.WriteString(fmt.Sprintf("type %sInput struct {\n", componentName))
		builder.WriteString(structFieldsSource(inputType))
		builder.WriteString("}\n\n")
	}

	// Output struct — always render directly (view types may not be registered yet)
	g.renderOutputStruct(&builder, componentName, embedURI, outputParams, outputType)

	// EmbedFS method
	if g.WithEmbed && inputType != nil {
		builder.WriteString(fmt.Sprintf("func (i *%sInput) EmbedFS() *embed.FS {\n", componentName))
		builder.WriteString(fmt.Sprintf("\treturn &%sFS\n", componentName))
		builder.WriteString("}\n\n")
	}

	// Write file
	if err := os.MkdirAll(packageDir, 0o755); err != nil {
		return nil, err
	}
	dest := filepath.Join(packageDir, fileName)
	if err := writeAtomic(dest, []byte(builder.String()), 0o644); err != nil {
		return nil, err
	}

	var typeNames []string
	if inputType != nil {
		typeNames = append(typeNames, componentName+"Input")
	}
	if outputType != nil {
		typeNames = append(typeNames, componentName+"Output")
	}
	if shapeResult != nil {
		typeNames = append(typeNames, shapeResult.Types...)
	}

	return &ComponentCodegenResult{
		FilePath:    dest,
		PackagePath: packagePath,
		PackageName: packageName,
		Types:       typeNames,
	}, nil
}

// renderOutputStruct writes the output struct definition.
// For reader components, it generates the standard pattern:
//
//	type XxxOutput struct {
//	    response.Status `parameter:",kind=output,in=status" json:",omitempty"`
//	    Data []*XxxView  `parameter:",kind=output,in=view" view:"xxx" sql:"uri=xxx/xxx.sql"`
//	}
func (g *ComponentCodegen) renderOutputStruct(builder *strings.Builder, componentName, embedURI string, outputParams state.Parameters, outputType reflect.Type) {
	rootView := g.Component.RootView
	viewType := componentName + "View"

	builder.WriteString(fmt.Sprintf("type %sOutput struct {\n", componentName))

	// Check if there's an explicit status parameter
	hasStatus := false
	for _, p := range outputParams {
		if p != nil && p.In != nil && p.In.Name == "status" {
			hasStatus = true
		}
	}
	if !hasStatus {
		builder.WriteString("\tresponse.Status `parameter:\",kind=output,in=status\" json:\",omitempty\"`\n")
	}

	for _, p := range outputParams {
		if p == nil || p.In == nil {
			continue
		}
		switch p.In.Name {
		case "view":
			cardinality := string(p.Schema.Cardinality)
			typePrefix := "[]*"
			if cardinality == string(state.One) {
				typePrefix = "*"
			}
			fieldName := p.Name
			if fieldName == "" || fieldName == "Output" {
				fieldName = "Data"
			}
			tag := fmt.Sprintf(`parameter:",kind=output,in=view" view:"%s" sql:"uri=%s/%s.sql"`,
				rootView, embedURI, rootView)
			if p.Tag != "" && strings.Contains(p.Tag, "anonymous") {
				tag += ` anonymous:"true"`
			}
			builder.WriteString(fmt.Sprintf("\t%s %s%s `%s`\n", fieldName, typePrefix, viewType, tag))
		case "status":
			builder.WriteString(fmt.Sprintf("\tresponse.Status `parameter:\",kind=output,in=status\" json:\",omitempty\"`\n"))
		default:
			// Other output parameters (meta, etc.)
			typeName := "interface{}"
			if p.Schema != nil && p.Schema.Name != "" {
				typeName = p.Schema.Name
			}
			builder.WriteString(fmt.Sprintf("\t%s %s `parameter:\",kind=output,in=%s\"`\n", p.Name, typeName, p.In.Name))
		}
	}

	builder.WriteString("}\n\n")
}

// resolveOutputWildcardTypes resolves output parameters with wildcard type `?` or empty
// schema to the view entity type. The legacy translator does this in updateParameterWithComponentOutputType.
func (g *ComponentCodegen) resolveOutputWildcardTypes(params state.Parameters, componentName string) {
	viewType := componentName + "View"
	for _, p := range params {
		if p == nil || p.In == nil {
			continue
		}
		if p.In.Kind != state.KindOutput {
			continue
		}
		if p.Schema == nil {
			p.Schema = &state.Schema{}
		}
		// If schema type is wildcard or empty, resolve to the view type
		if p.Schema.Name == "" || p.Schema.DataType == "" || p.Schema.DataType == "?" {
			p.Schema.Name = viewType
			p.Schema.DataType = "*" + viewType
			if p.Schema.Cardinality == "" {
				p.Schema.Cardinality = state.Many
			}
		}
		// Add view tag if missing
		if p.In.Name == "view" && !strings.Contains(p.Tag, "view:") {
			rootView := g.Component.RootView
			p.Tag += fmt.Sprintf(` view:"%s"`, rootView)
		}
	}
}

// defaultOutputParameters creates the default output parameters for a reader component:
// - Data: the main view data (anonymous, kind=output, in=view)
// - Status: response status (anonymous, kind=output, in=status)
// This mirrors internal/translator output.go ensureOutputParameters.
func (g *ComponentCodegen) defaultOutputParameters(componentName string) state.Parameters {
	rootView := g.Component.RootView
	viewType := componentName + "View"

	// Data parameter — references the root view
	dataParam := &state.Parameter{
		Name: "Data",
		In:   state.NewOutputLocation("view"),
		Tag:  fmt.Sprintf(`anonymous:"true" view:"%s"`, rootView),
		Schema: &state.Schema{
			Name:        viewType,
			DataType:    "*" + viewType,
			Cardinality: state.Many,
		},
	}

	// Status parameter — response.Status
	statusParam := &state.Parameter{
		Name:   "Status",
		In:     state.NewOutputLocation("status"),
		Tag:    `anonymous:"true" json:",omitempty"`,
		Schema: &state.Schema{DataType: "response.Status"},
	}

	return state.Parameters{dataParam, statusParam}
}

func (g *ComponentCodegen) withRegister() bool {
	if g.WithRegister == nil {
		return true // default enabled
	}
	return *g.WithRegister
}

func (g *ComponentCodegen) componentName() string {
	name := ""
	if g.Component != nil {
		name = g.Component.RootView
	}
	if name == "" && g.Resource != nil && len(g.Resource.Views) > 0 {
		name = g.Resource.Views[0].Name
	}
	if name == "" {
		name = "Component"
	}
	return state.SanitizeTypeName(name)
}

func (g *ComponentCodegen) buildImports() []string {
	var imports []string
	if g.withRegister() {
		imports = append(imports,
			"reflect",
			"github.com/viant/xdatly/types/core",
		)
		checksumPkg := "github.com/viant/xdatly/types/custom/checksum"
		if g.PackagePath != "" {
			if idx := strings.LastIndex(g.PackagePath, "/pkg/"); idx != -1 {
				candidate := g.PackagePath[:idx] + "/pkg/checksum"
				parent, _ := filepath.Split(candidate)
				if !strings.HasSuffix(parent, "dependency/") {
					candidate = filepath.Join(parent, "dependency", "checksum")
				}
				checksumPkg = filepath.ToSlash(candidate)
			}
		}
		imports = append(imports, checksumPkg)
	}
	imports = append(imports, "github.com/viant/xdatly/handler/response")
	if g.WithEmbed {
		imports = append(imports, "embed")
	}
	return imports
}

func structFieldsSource(rType reflect.Type) string {
	if rType == nil {
		return ""
	}
	for rType.Kind() == reflect.Ptr {
		rType = rType.Elem()
	}
	if rType.Kind() != reflect.Struct {
		return ""
	}
	var b strings.Builder
	for i := 0; i < rType.NumField(); i++ {
		f := rType.Field(i)
		if !f.IsExported() {
			continue
		}
		b.WriteString("\t" + f.Name + " " + f.Type.String())
		if f.Tag != "" {
			b.WriteString(" `" + string(f.Tag) + "`")
		}
		b.WriteString("\n")
	}
	return b.String()
}

func resourceToCodegenDoc(resource *view.Resource, typeCtx *typectx.Context) *shape.Document {
	root := map[string]any{}
	var views []any
	for _, v := range resource.Views {
		if v == nil {
			continue
		}
		viewMap := map[string]any{
			"Name":  v.Name,
			"Table": v.Table,
			"Mode":  string(v.Mode),
		}
		if v.Schema != nil {
			schema := map[string]any{}
			if v.Schema.Name != "" {
				schema["Name"] = v.Schema.Name
			}
			viewMap["Schema"] = schema
		}
		if len(v.Columns) > 0 {
			var cols []any
			for _, c := range v.Columns {
				if c == nil {
					continue
				}
				cols = append(cols, map[string]any{
					"Name":     c.Name,
					"DataType": c.DataType,
					"Nullable": c.Nullable,
				})
			}
			viewMap["Columns"] = cols
		}
		views = append(views, viewMap)
	}
	root["Resource"] = map[string]any{"Views": views}
	return &shape.Document{Root: root, TypeContext: typeCtx}
}
