init:
  appPath: $WorkingDir(../../)
pipeline:
  datly:
    stop:
      action: process:stop
      target: $target
      input: custom_datly

    start:
      action: process:start
      sleepTimeMs: 0
      target: $target
      directory: /tmp/
      checkError: true
      immuneToHangups: true
      env:
        TEST: 1
      command: $appPath/.extension/datly -c=$appPath/.extension/repo/dev/Datly/config.json > /tmp/custom_datly.out