

pipeline:
  register:
    action: dsunit:register
    datastore: dev
    recreate: false
    config:
      driverName: mysql
      descriptor: '[username]:[password]@tcp(${dbIP.mysql}:3306)/[dbname]?parseTime=true'
      credentials: $mysqlCredentials
