pipeline:
  printParent:
    action: exec:run
    commands:
      - echo 'over_cases -> ${mode} | ${datlyPath}'


  printStep:
    action: print
    message: $AsJSON($state)

  prepare_custom_datly:
    tag: $pathMatch
    description: '@info'
    subPath: 'cases/${index}_*'

    range: 1..005
    template:
      checkSkip:
        action: nop
        comments: use case init
        skip: $HasResource(${path}/skip.txt)

      rule:
        description: generate datly rule with SQLx (SQL extension)
        action: run
        request: '@rule'