pipeline:
  printParent:
    action: exec:run
    commands:
      - echo 'over_cases -> ${mode} | ${datlyPath}'

  prepare_custom_datly:
    tag: $pathMatch
    description: '@info'

    subPath: 'cases/${index}_*'
    data:
      '[]gen': '@gen'


    range: 1..003
    template:
      checkSkip:
        action: nop
        comments: use case init
        skip: $HasResource(${path}/skip.txt)

      setMode:
        action: nop
        init:
          mode: ${parent.mode}
          datlyPath: ${parent.datlyPath}
          'state.aPath': ${path}

      rule:
        description: generate datly rule with SQLx (SQL extension)
        action: run
        request: '@rule'