init:
  appPath: $WorkingDirectory()
  state:
    step: step1_generate
    datlyPath: '/tmp/datly'

pipeline:
  setSdk:
    action: sdk.set
    target: $target
    sdk: go:1.20

  cleanup:
    action: exec:run
    description: clean previous tests
    target: '$target'
    checkError: true
    commands:
      - mkdir -p ${appPath}/autogen
      - rm -rf ${appPath}/autogen

  database:
    action: run
    request: '@db'

  prepareTests:
    action: run
    request: '@over_cases'

  setCopyPluginsState:
    action: nop
    init:
      'state.step': step2_before_replace

  generateRules:
    action: run
    request: '@over_cases'

  rebuild_datly:
    action: exec:run
    target: '$target'
    checkError: true
    commands:
      - cd ${appPath}/e2e/custom_datly/.extension/.build/ext
      - go mod tidy
      - cd ${appPath}/e2e/custom_datly/.extension/pkg
      - go get github.com/viant/xdatly/handler@01ca1dc
      - go mod tidy
      - cd $appPath/e2e/custom_datly/.extension/.build/datly
      - go mod edit -replace github.com/viant/xdatly/extension=${appPath}/e2e/custom_datly/.extension/.build/ext
      - go mod edit -replace github.com/viant/datly_ext=${appPath}/e2e/custom_datly/.extension/pkg
      - go mod tidy
      - /tmp/datly build -p='${appPath}/e2e/custom_datly/.extension' -d='${appPath}/e2e/custom_datly/.extension'  -r=standalone -o=darwin -a=amd64 -v=1.20.5 -f='' -b='-trimpath'
      - chmod u+x ${appPath}/e2e/custom_datly/.extension/datly





  setGeneratePluginsState:
    action: nop
    init:
      'state.step': step3_plugin

  generatePlugins:
    action: run
    request: '@over_cases'



  buildPlugin:
    action: exec:run
    target: '$target'
    checkError: true
    commands:
      - cd ${appPath}/e2e/custom_datly/.extension/pkg
      - go mod tidy
      - $appPath/e2e/custom_datly/.extension/datly plugin -s=${appPath}/e2e/custom_datly/.extension/ -d=${appPath}/e2e/custom_datly/.extension/repo/dev/Datly/plugins -v=1.20.5 -a=amd64 -b='-trimpath'

  app:
    description: start datly app with rule generted from SQLs
    action: run
    request: '@app'

  setRunTestsState:
    action: nop
    init:
      'state.step': step4_run_test


  runTests:
    action: run
    description: running test cases
    request: '@over_cases'
