package sequencer

import (
	"context"
	"fmt"
	"reflect"
	"testing"
	"time"

	"github.com/viant/sqlx/metadata/info/dialect"
	"github.com/viant/sqlx/testutil/reservationdb"
)

type liveSequenceRow struct {
	ID   *int64 `sqlx:"id,primaryKey,autoincrement"`
	Name string `sqlx:"name"`
}

func TestSequenceLivePostgresSparseExactValues(t *testing.T) {
	for _, descending := range []bool{false, true} {
		t.Run(fmt.Sprint(descending), func(t *testing.T) {
			h := reservationdb.Open(t, "postgres")
			seq := h.Table("numbers")
			definition := " START 1 INCREMENT 1 MINVALUE 1 MAXVALUE 1000"
			if descending {
				definition = " START -1 INCREMENT -1 MINVALUE -1000 MAXVALUE -1"
			}
			h.Exec(t, "CREATE SEQUENCE "+seq+definition+" CACHE 3", "CREATE TABLE "+h.Table("records")+"(id BIGINT DEFAULT nextval('"+seq+"'::regclass),name TEXT)")
			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
			defer cancel()
			a, err := h.DB.BeginTx(ctx, nil)
			if err != nil {
				t.Fatal(err)
			}
			defer a.Rollback()
			b, err := h.Other(t).BeginTx(ctx, nil)
			if err != nil {
				t.Fatal(err)
			}
			defer b.Rollback()
			var warm int64
			if err = a.QueryRowContext(ctx, "SELECT nextval($1::regclass)", seq).Scan(&warm); err != nil {
				t.Fatal(err)
			}
			if err = b.QueryRowContext(ctx, "SELECT nextval($1::regclass)", seq).Scan(&warm); err != nil {
				t.Fatal(err)
			}
			supplied := int64(2)
			want := []int64{3, 7, 8}
			if descending {
				supplied = -2
				want = []int64{-3, -7, -8}
			}
			rows := []*liveSequenceRow{nil, {Name: "first"}, {ID: &supplied}, {Name: "second"}, {Name: "third"}, nil}
			s := New(h.DB, a)
			if err = s.Allocate(ctx, h.Table("records"), rows, "ID"); err != nil {
				t.Fatal(err)
			}
			actual := []int64{*rows[1].ID, *rows[3].ID, *rows[4].ID}
			if !reflect.DeepEqual(actual, want) || rows[2].ID != &supplied || rows[0] != nil || rows[5] != nil {
				t.Fatalf("exact sparse assignment: %v want %v", actual, want)
			}
			var count int
			if err = a.QueryRowContext(ctx, "SELECT count(*) FROM "+h.Table("records")).Scan(&count); err != nil || count != 0 {
				t.Fatalf("allocation wrote entities: %d %v", count, err)
			}
		})
	}
}

func TestSequenceLiveCompositeFieldAuthority(t *testing.T) {
	for _, driver := range []string{"mysql", "postgres"} {
		t.Run(driver, func(t *testing.T) {
			h := reservationdb.Open(t, driver)
			idType := "BIGINT NOT NULL AUTO_INCREMENT"
			suffix := " ENGINE=InnoDB"
			if driver == "postgres" {
				idType = "BIGINT GENERATED BY DEFAULT AS IDENTITY"
				suffix = ""
			}
			h.Exec(t, "CREATE TABLE "+h.Table("records")+"(tenant_id BIGINT NOT NULL,id "+idType+",PRIMARY KEY(tenant_id,id),UNIQUE(id))"+suffix, "INSERT INTO "+h.Table("records")+"(tenant_id) VALUES(100)")
			type row struct {
				Tenant int64 `sqlx:"tenant_id,primaryKey"`
				ID     int64 `sqlx:"id,primaryKey"`
			}
			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
			defer cancel()
			tx, err := h.DB.BeginTx(ctx, nil)
			if err != nil {
				t.Fatal(err)
			}
			defer tx.Rollback()
			s := New(h.DB, tx).WithStrategy(dialect.PresetIDWithReservation)
			supplied := &row{Tenant: 100, ID: 2}
			generated := &row{Tenant: 100}
			if err = s.Reserve(ctx, h.Table("records"), supplied, "ID"); err != nil {
				t.Fatal(err)
			}
			if err = s.Allocate(ctx, h.Table("records"), generated, "ID"); err != nil {
				t.Fatal(err)
			}
			if generated.ID != 3 || generated.Tenant != 100 || supplied.ID != 2 {
				t.Fatalf("wrong column authority: %+v %+v", generated, supplied)
			}
		})
	}
}
