init:
  parentPath: $parent.path
  expect: $LoadData('${parentPath}/expect.json')
pipeline:

  test:
    action: http/runner:send
    requests:
      - Method: GET
        URL: ${awsEndpointURL}v1/api/dev/performance-async
        Expect:
          Code: 200
