init:
  '!configBucket': $params.configBucket
  appName: DatlyAPIGW
  appPath: $WorkingDirectory(./../../..)
  appArchive: ${appPath}/gateway/runtime/apigw/app/datly.zip
  privilegePolicy: policy/datly.json
  awsCredentials: aws-e2e
  configMap: $LoadJSON('resource/config.json')
  datlyConfig:  $AsJSON(${configMap})

pipeline:

  info:
    action: print
    message: $AsJSON(${datlyConfig})

  uploadConfig:
    action: storage:upload
    expand: true
    sourceKey: datlyConfig
    dest:
      URL: s3://${configBucket}/${appName}/config.json
      credentials: $awsCredentials

  set_sdk:
    action: sdk.set
    target: $target
    sdk: go:1.17

  build:
    package:
      action: exec:run
      comments: vendor build for deployment speedup
      target: $target
      checkError: true
      commands:
        - cd ${appPath}/gateway/runtime/apigw/app/
        - export GOOS=linux
        - go mod tidy
        - go build datly.go
        - zip -j ${appArchive} datly

  deploy:
    deploy:
      action: aws/lambda:deploy
      credentials: $awsCredentials
#       vpcMatcher:
#         vpc:
#           name: mysql-e2e

      functionname: ${appName}
      runtime:  go1.x
      timeout: 540
      environment:
        variables:
          CONFIG_URL:  s3://${configBucket}/${appName}/config.json
          LOGGING: true
      handler: datly
      code:
        zipfile: $LoadBinary(${appArchive})
      rolename: DatlyRole
      define:
        - policyname: lambda-datly-execution-role
          policydocument: $Cat('${privilegePolicy}')
      attach:
        - policyarn: arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - policyarn: arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
    deployGatewayAPI:
      redeploy: true
      action: aws/apigateway:deployAPI
      credentials: $awsCredentials
      '@name': DatlyAPI
      resources:
        - path: /
          methods:
            - httpMethod: GET
              functionname: ${appName}
        - path: /{proxy+}
          methods:
            - httpMethod: GET
              functionname: ${appName}

  clean:
    action: exec:run
    comments: vendor build for deployment speedup
    target: $target
    checkError: true
    commands:
      - cd ${appPath}/gateway/runtime/apigw/app/
      - rm datly
      - rm ${appArchive}


post:
  awsEndpointURL: ${deployGatewayAPI.EndpointURL}
