init:
  parentPath: $parent.path
pipeline:

  test:
    action: http/runner:send
    requests:
      - Method: POST
        URL: http://127.0.0.1:8080/v1/api/dev/basic/custom-json
        JsonBody:
          ID: 0
          Name: "Bar"
          Ints:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
        Expect:
         Code: 200
         JSONBody:
           name: "Bar"
           ints: 55