CREATE TABLE roots(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL);
CREATE TABLE carriers(id INTEGER PRIMARY KEY AUTOINCREMENT,root_id INTEGER NOT NULL REFERENCES roots(id),name TEXT NOT NULL);
CREATE TABLE children(id INTEGER PRIMARY KEY AUTOINCREMENT,root_id INTEGER NOT NULL REFERENCES roots(id),carrier_id INTEGER NOT NULL REFERENCES carriers(id),name TEXT NOT NULL);
