init:
  appName: Datly
  yesterday: $FormatTime('yesterdayInUTC', 'yyyy-MM-dd HH:mm:ss')
  today: $FormatTime('nowInUTC', 'yyyy-MM-dd HH:mm:ss')
  '!authWith': $params.authWith
  '!configBucket': $params.configBucket
  target:
    URL: ssh://localhost/
    credentials: localhost
  appPath: $WorkingDirectory(../..)
  bqCredentials: $authWith
  gcpProjectID: $bqCredentials
  awsCredentials: aws-e2e

pipeline:
  init:
    description: initialise test (docker,database,build app)
    system:
      action: run
      request: '@system'
      tasks: '*'

    datastore:
      action: run
      request: '@datastore/datastore.yaml'
      tasks: '*'

  build:
    action: run
    request: '@build'
    tasks: '*'

  test:
    action: run
    description: run regression test
    request: '@regression/regression'
