package generate

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/viant/datly/internal/testharness"
	"github.com/viant/datly/spec"
)

func TestFilenameLayoutMigration(t *testing.T) {
	for _, scenario := range []string{"unchanged", "edited shape", "edited handler", "unowned destination", "no fingerprint"} {
		t.Run(scenario, func(t *testing.T) {
			root := t.TempDir()
			testharness.WriteGeneratedGoMod(t, root)
			dir := filepath.Join(root, "orders")
			input := Input{Component: customHandlerComponent(), TargetPackage: "example.com/generated/orders", ProjectRoot: root, PackageName: "orders", ContractHandler: parseContractHandlerAsset(t, "NewOrdersHandler", validContractHandlerSource())}
			// The previous release's concrete filenames and manifest format. All are
			// generated by the native persistence owner to retain real ownership evidence.
			previous := input.Component.Clone()
			previous.Settings = &spec.Settings{Generation: &spec.GenerationSettings{ViewFile: "orders.go", InputFile: "orders_input.go", OutputFile: "orders_output.go", RouterFile: "orders_router.go", HandlerFile: "orders_handler_gen.go", LinksFile: "orders_link_gen.go"}}
			old := input
			old.Component = previous
			if _, err := New(old).Generate(dir); err != nil {
				t.Fatal(err)
			}
			authored := filepath.Join(dir, "application.go")
			if err := os.WriteFile(authored, []byte("package orders\nconst Authored = true\n"), 0644); err != nil {
				t.Fatal(err)
			}
			switch scenario {
			case "edited shape", "edited handler":
				name := "orders_input.go"
				if scenario == "edited handler" {
					name = "orders_handler_gen.go"
				}
				file := filepath.Join(dir, name)
				content, err := os.ReadFile(file)
				if err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(file, append(content, []byte("\n// authored edit\n")...), 0644); err != nil {
					t.Fatal(err)
				}
			case "unowned destination":
				if err := os.WriteFile(filepath.Join(dir, "input.go"), []byte("package orders\nconst UserFile = true\n"), 0644); err != nil {
					t.Fatal(err)
				}
			case "no fingerprint":
				manifest, err := readScaffoldManifest(dir)
				if err != nil {
					t.Fatal(err)
				}
				manifest.Fingerprints = nil
				if err := writeScaffoldManifest(dir, manifest.Owner, manifest.Files, manifest); err != nil {
					t.Fatal(err)
				}
			}
			before, err := readScaffoldSnapshot(root)
			if err != nil {
				t.Fatal(err)
			}
			plan, err := New(input).Plan()
			if err != nil {
				t.Fatal(err)
			}
			validate := plan.ValidateDestination(dir)
			_, generate := New(input).Generate(dir)
			if scenario != "unchanged" {
				if validate == nil || generate == nil {
					t.Fatalf("unsafe migration accepted: validate=%v generate=%v", validate, generate)
				}
				after, err := readScaffoldSnapshot(root)
				if err != nil || !reflect.DeepEqual(before, after) {
					t.Fatalf("failed migration changed package: %v", err)
				}
				return
			}
			if validate != nil || generate != nil {
				t.Fatalf("migration: validate=%v generate=%v", validate, generate)
			}
			for _, name := range []string{"orders_input.go", "orders_output.go", "orders_router.go", "orders_handler_gen.go", "orders_link_gen.go"} {
				if _, err := os.Stat(filepath.Join(dir, name)); !os.IsNotExist(err) {
					t.Fatalf("obsolete file %s remains: %v", name, err)
				}
			}
			if _, err := os.Stat(authored); err != nil {
				t.Fatal("authored file lost", err)
			}
			if _, err := New(input).Generate(dir); err != nil {
				t.Fatal("second regeneration", err)
			}
		})
	}
}

func TestFilenameLayoutInvalidControlsAreAtomic(t *testing.T) {
	for _, configure := range []struct {
		name     string
		settings spec.GenerationSettings
	}{
		{"prefix escape", spec.GenerationSettings{FilePrefix: "../"}},
		{"handler path", spec.GenerationSettings{HandlerFile: "../handler.go"}},
		{"unused lifecycle path", spec.GenerationSettings{LifecycleFile: "nested/hook.go"}},
		{"resources path", spec.GenerationSettings{ResourcesFile: "/tmp/resources.go"}},
		{"support path", spec.GenerationSettings{SupportFiles: map[string]string{"frames": "../frame.go"}}},
		{"support hidden", spec.GenerationSettings{SupportFiles: map[string]string{"frames": "_frame.go"}}},
		{"prefix override collision", spec.GenerationSettings{FilePrefix: "orders_", InputFile: "orders_router.go"}},
		{"role collision", spec.GenerationSettings{HandlerFile: "router.go"}},
	} {
		t.Run(configure.name, func(t *testing.T) {
			dir := t.TempDir()
			input := Input{Component: customHandlerComponent(), TargetPackage: "example.com/orders", ContractHandler: parseContractHandlerAsset(t, "NewOrdersHandler", validContractHandlerSource())}
			if _, err := New(input).Generate(dir); err != nil {
				t.Fatal(err)
			}
			before, err := readScaffoldSnapshot(dir)
			if err != nil {
				t.Fatal(err)
			}
			input.Component.Settings = &spec.Settings{Generation: &configure.settings}
			if _, err := New(input).Generate(dir); err == nil {
				t.Fatal("invalid filename control accepted")
			}
			after, err := readScaffoldSnapshot(dir)
			if err != nil || !reflect.DeepEqual(before, after) {
				t.Fatalf("invalid control changed files: %v", err)
			}
		})
	}
}

func TestFilenameLayoutHandlerPrefixAndOverride(t *testing.T) {
	for _, prefix := range []string{"", "orders_"} {
		for _, supplied := range []string{"", "supplied.go"} {
			for _, override := range []string{"", "execute.go"} {
				component := customHandlerComponent()
				component.Settings = &spec.Settings{Generation: &spec.GenerationSettings{FilePrefix: prefix, HandlerFile: override}}
				asset := parseContractHandlerAsset(t, "NewOrdersHandler", validContractHandlerSource())
				asset.Destination = supplied
				plan, err := New(Input{Component: component, TargetPackage: "example.com/orders", ContractHandler: asset}).Plan()
				if err != nil {
					t.Fatal(err)
				}
				expected := prefix + "handler.go"
				if supplied != "" {
					expected = supplied
				}
				if override != "" {
					expected = override
				}
				if plan.ContractHandler.Destination != expected {
					t.Fatal(plan.ContractHandler.Destination)
				}
			}
		}
	}
}

func TestFilenameLayoutSharedPackage(t *testing.T) {
	for _, scenario := range []string{"defaults conflict", "same prefix conflict", "distinct prefixes", "exact override conflict"} {
		t.Run(scenario, func(t *testing.T) {
			root := t.TempDir()
			testharness.WriteGeneratedGoMod(t, root)
			dir := filepath.Join(root, "shared")
			before := scaffoldSnapshot{}
			for i, name := range []string{"Orders", "Users"} {
				settings := &spec.GenerationSettings{}
				switch scenario {
				case "same prefix conflict":
					settings.FilePrefix = "same_"
				case "distinct prefixes", "exact override conflict":
					settings.FilePrefix = strings.ToLower(name) + "_"
				}
				if scenario == "exact override conflict" {
					settings.InputFile = "shared_input.go"
				}
				input := Input{Component: &spec.Component{Name: name, RootView: &spec.View{Name: name}, Routes: []*spec.Route{{Method: "GET", Path: "/" + name}}, Settings: &spec.Settings{Generation: settings}}, TargetPackage: "example.com/generated/shared", ProjectRoot: root, PackageName: "shared"}
				_, err := New(input).Generate(dir)
				if i == 1 && scenario != "distinct prefixes" {
					if err == nil {
						t.Fatal("implicit collision fallback accepted")
					}
					after, e := readScaffoldSnapshot(root)
					if e != nil || !reflect.DeepEqual(before, after) {
						t.Fatal("collision changed package", e)
					}
					break
				}
				if err != nil {
					t.Fatal(err)
				}
				before, err = readScaffoldSnapshot(root)
				if err != nil {
					t.Fatal(err)
				}
			}
		})
	}
}
