package generate

import (
	"crypto/sha256"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"github.com/viant/datly/internal/packageasset"
	xshape "github.com/viant/x/shape"
)

func generatedHeader(owner string) string {
	return "// Code generated by Datly for " + owner + "; DO NOT EDIT.\n\n"
}

// generatedOwner recognizes ordinary generated-source comments, including the
// scaffold comments emitted by older Datly versions for deterministic migration.
func generatedOwner(content []byte) string {
	for _, line := range strings.Split(string(content), "\n") {
		if strings.HasPrefix(line, "// Code generated by Datly for ") && strings.HasSuffix(line, "; DO NOT EDIT.") {
			return strings.TrimSuffix(strings.TrimPrefix(line, "// Code generated by Datly for "), "; DO NOT EDIT.")
		}
		for _, phrase := range []string{" is the generated input scaffold for ", " is the generated output scaffold for ", " is the generated component scaffold for ", " is generated canonical view metadata for "} {
			if strings.HasPrefix(line, "// ") {
				if _, owner, ok := strings.Cut(line, phrase); ok {
					return strings.TrimSuffix(strings.TrimSpace(owner), ".")
				}
			}
		}
	}
	return ""
}

// prepareCurrent discovers obsolete files from current source. It never reads
// historical ownership or fingerprints. Linked contracts and create-once hooks
// are outside this generated artifact set.
func (p *scaffoldPersistence) prepareCurrent(target string) error {
	p.renames = map[string]bool{}
	desired, err := p.desiredFiles(target)
	if err != nil {
		return err
	}
	keep := map[string]bool{}
	for _, name := range desired {
		keep[name] = true
	}
	entries, err := os.ReadDir(target)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	legacyComponent := false
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		content, err := os.ReadFile(filepath.Join(target, entry.Name()))
		if err != nil {
			return err
		}
		if generatedOwner(content) == p.owner {
			legacyComponent = true
		}
	}
	referenced := map[string]bool{}
	retiredAssets := map[string]bool{}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(target, entry.Name()))
		if err != nil {
			return err
		}
		if !strings.Contains(string(data), "//go:embed") {
			continue
		}
		assets, err := packageasset.SourceEmbedFiles(target, data)
		// Replaced generated source is disposable, even if it no longer parses.
		if err != nil {
			if generatedOwner(data) == p.owner {
				continue
			}
			return err
		}
		for _, asset := range assets {
			if generatedOwner(data) == p.owner {
				retiredAssets[asset] = true
			} else {
				referenced[asset] = true
			}
		}
	}
	for asset := range retiredAssets {
		if !keep[asset] && !referenced[asset] {
			p.renames[filepath.FromSlash(asset)] = true
		}
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		content, err := os.ReadFile(filepath.Join(target, entry.Name()))
		if err != nil {
			return err
		}
		owner := generatedOwner(content)
		if keep[entry.Name()] && owner == "" && !(legacyComponent && p.matchesCurrentDeclarations(entry.Name(), content)) {
			return fmt.Errorf("generated file %q collides with an unowned package file", entry.Name())
		}

		if keep[entry.Name()] && owner != "" && owner != p.owner {
			return fmt.Errorf("generated destination %s belongs to component %s", entry.Name(), owner)
		}
		if owner == p.owner && !keep[entry.Name()] && !p.linkedDestination(entry.Name()) && !p.linkedSource(content) {
			p.renames[entry.Name()] = true
		}
	}
	for _, name := range p.removals {
		relative, err := managedRelativePath(name)
		if err != nil {
			return err
		}
		if relative == "" || keep[relative] || p.linkedDestination(relative) {
			continue
		}
		// Legacy artifact removal is explicit in the current plan. Protect authored
		// Go files rather than treating their conventional filename as provenance.
		content, err := os.ReadFile(filepath.Join(target, relative))
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return err
		}
		if generatedOwner(content) == p.owner {
			p.renames[relative] = true
		}
	}
	return p.preserveEntityMethods(target, target)
}

func (p *scaffoldPersistence) linkedDestination(name string) bool {
	if p.plan == nil {
		return false
	}
	return p.plan.Input.Ownership == ContractLinked && (p.plan.Input.Package == p.plan.Package || p.plan.Input.Package == "" && !strings.Contains(p.plan.Input.Type, ".")) && name == p.plan.Input.Destination || p.plan.Output.Ownership == ContractLinked && (p.plan.Output.Package == p.plan.Package || p.plan.Output.Package == "" && !strings.Contains(p.plan.Output.Type, ".")) && name == p.plan.Output.Destination
}

// Fingerprints are transient publication snapshots only, never ownership data.
func scaffoldFingerprint(content []byte) string { return fmt.Sprintf("%x", sha256.Sum256(content)) }

// Linked declarations in this package are explicit Go authority during reload.
func (p *scaffoldPersistence) linkedSource(content []byte) bool {
	if p.plan == nil {
		return false
	}
	names := map[string]bool{}
	for _, c := range []ContractPlan{p.plan.Input, p.plan.Output} {
		if c.Ownership == ContractLinked && c.Package == p.plan.Package {
			names[strings.TrimPrefix(c.Type, p.plan.PackageName()+".")] = true
		}
	}
	for _, v := range p.plan.Views {
		if v.Ownership == ViewLinked && v.Package == p.plan.Package {
			names[strings.TrimPrefix(v.Type, p.plan.PackageName()+".")] = true
		}
	}
	parsed, err := parser.ParseFile(token.NewFileSet(), "shapes.go", content, 0)
	if err != nil {
		return false
	}
	for _, d := range parsed.Decls {
		g, ok := d.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, s := range g.Specs {
			if typ, ok := s.(*ast.TypeSpec); ok && names[typ.Name.Name] {
				return true
			}
		}
	}
	return false
}

// Earlier generators omitted the standard header on support/resource files.
// Upgrade them at their declared destinations using the component holder and
// current native declarations, never a package sidecar or a filename guess.
func (p *scaffoldPersistence) matchesCurrentDeclarations(name string, content []byte) bool {
	for _, file := range p.files {
		if filepath.Base(file.Path) != name {
			continue
		}
		current, expected, err := legacySourceDeclarations([]byte(file.Content))
		if err != nil {
			return false
		}
		previous, declarations, err := legacySourceDeclarations(content)
		if err != nil || previous.Package != current.Package || len(declarations) == 0 {
			return false
		}
		for declaration := range declarations {
			if !expected[declaration] {
				return false
			}
		}
		return true
	}
	return false
}

// SourceParser.Declarations intentionally excludes receiver methods. Complete
// current-source identity with native AST method receivers/signatures so old
// setter/index files can be upgraded without claiming files by their names.
func legacySourceDeclarations(content []byte) (*xshape.Source, map[string]bool, error) {
	source, err := (xshape.SourceParser{}).Parse(content)
	if err != nil {
		return nil, nil, err
	}
	declarations := map[string]bool{}
	for _, name := range source.Declarations {
		declarations["declaration:"+name] = true
	}
	file, err := parser.ParseFile(token.NewFileSet(), "legacy.go", content, parser.SkipObjectResolution)
	if err != nil {
		return nil, nil, err
	}
	imports := map[string]string{}
	for alias, imported := range source.Imports {
		imports[alias] = imported.Path
	}
	for _, declaration := range file.Decls {
		method, ok := declaration.(*ast.FuncDecl)
		if !ok {
			continue
		}
		if method.Recv == nil {
			// Initializers are also excluded by SourceParser. An extra application
			// initializer must not be silently claimed as generated support.
			if method.Name.Name == "init" {
				declarations["initializer:init"] = true
			}
			continue
		}
		if len(method.Recv.List) != 1 {
			return nil, nil, fmt.Errorf("method receiver is required")
		}
		receiver, err := canonicalType(method.Recv.List[0].Type, imports, source.Package)
		if err != nil {
			return nil, nil, err
		}
		signature, err := canonicalType(method.Type, imports, source.Package)
		if err != nil {
			return nil, nil, err
		}
		declarations["method:"+receiver+"."+method.Name.Name+":"+signature] = true
	}
	return source, declarations, nil
}
