package generate

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

// prepareFiles retains the raw generator proposal separately from structural
// merge results, including when a persistence request is validated or retried.
func (p *scaffoldPersistence) prepareFiles() {
	if p.proposal == nil {
		p.proposal = append([]EmittedFile(nil), p.files...)
	}
	p.files = append([]EmittedFile(nil), p.proposal...)
}

// protectArtifacts authorizes content changes and stale deletion against the
// last generated bytes, not filename ownership alone. It returns the next
// manifest's baselines without adopting edits to retained artifacts.
func (p *scaffoldPersistence) protectArtifacts(target, existing string, previous *scaffoldManifest, desired []string) (map[string]string, error) {
	proposed := map[string][]byte{}
	for _, file := range p.files {
		relative, err := managedPath(target, file.Path)
		if err != nil {
			return nil, err
		}
		proposed[relative] = []byte(file.Content)
	}
	keep := map[string]bool{}
	for _, file := range desired {
		keep[file] = true
	}
	shapes := p.shapeDestinations()
	paths := append([]string(nil), previous.Files...)
	sort.Strings(paths)
	result := map[string]string{}
	for _, file := range paths {
		relative, err := managedRelativePath(file)
		if err != nil {
			return nil, err
		}
		if relative == "" {
			return nil, fmt.Errorf("generated package manifest contains an empty file path")
		}
		if keep[relative] && previous.Fingerprints[relative] != "" {
			result[relative] = previous.Fingerprints[relative]
		}
		content, writing := proposed[relative]
		removing := !keep[relative]
		if !writing && !removing {
			continue
		}
		if writing && shapes[relative] && p.policy != GenerationPolicyOverwrite {
			continue
		} // exact-field merge already validated preservation
		current, err := os.ReadFile(filepath.Join(existing, relative))
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return nil, err
		}
		if writing && bytes.Equal(current, content) {
			continue
		} // identical desired bytes are safe even without an old baseline
		fingerprint := previous.Fingerprints[relative]
		if fingerprint == "" {
			return nil, fmt.Errorf("generated file %q has no trusted fingerprint: explicit migration required before replacement or removal", relative)
		}
		if fingerprint != scaffoldFingerprint(current) {
			return nil, fmt.Errorf("generated file %q was manually changed: regeneration would replace or remove edited content", relative)
		}
	}
	for relative, content := range proposed {
		// Linked resources are retained source bytes, not a fresh generator
		// proposal. Keep their prior baseline so edits cannot acquire ownership.
		if p.plan != nil && p.plan.Resources.retained(relative) {
			continue
		}
		// Exact generated-field edits must not grant deletion rights over
		// previously authored shape content. Retain its last trusted baseline.
		if shapes[relative] && p.customizedShapes[relative] {
			continue
		}
		result[relative] = scaffoldFingerprint(content)
	}
	return result, nil
}

func scaffoldFingerprint(content []byte) string {
	return fmt.Sprintf("sha256:%x", sha256.Sum256(content))
}
